### ISSUE TITLE
Loading the frozen model for deployment

### ISSUE THREAD

**Issue by fuzzyBatman** [qubvel/segmentation_models#100]
Did anyone freeze the trained model for deployment on a device on the edge?

I have trained a U-Net with a ResNet50 backbone. I am able to freeze the model.
The default input and output names are **data** and **sigmoid/Sigmoid** respectively.

But when I try to load the frozen model I get a ValueError. This could be a Tensorflow bug or I am not using it correctly, but I wanted to be sure it has indeed worked for someone.

The error message is:
```
Traceback (most recent call last):
  File "/home/fuzzybatman/.local/lib/python3.7/site-packages/tensorflow/python/framework/importer.py", line 426, in import_graph_def
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: NodeDef expected inputs '' do not match 1 inputs specified; Op<name=Const; signature= -> output:dtype; attr=value:tensor; attr=dtype:type>; NodeDef: {{node bn_data/cond/ones_like/Shape}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fuzzybatman/Workspace/ET4399-Extra_Project_[Okotech]/09 - UNet/frozen_predict.py", line 30, in <module>
    tf.import_graph_def(trt_graph, name='')
  File "/home/fuzzybatman/.local/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/fuzzybatman/.local/lib/python3.7/site-packages/tensorflow/python/framework/importer.py", line 430, in import_graph_def
    raise ValueError(str(e))
ValueError: NodeDef expected inputs '' do not match 1 inputs specified; Op<name=Const; signature= -> output:dtype; attr=value:tensor; attr=dtype:type>; NodeDef: {{node bn_data/cond/ones_like/Shape}}
```

`NodeDef expected inputs ''`

I have posted this on Tensorflow issues as well. [Issue 28532](https://github.com/tensorflow/tensorflow/issues/28532)

**Comment by fuzzyBatman** [comment]
My bad. Blindly copied the code from the internet.
Interchangeably used **keras** and **tensorflow.keras**

**Comment by kjodha** [comment]
@fuzzyBatman @qubvel @JordanMakesMaps How did you solve the problem loading a frozen graph? I need the input and output tensor names in order to run the predictions but every time I try to read the names, it throws up this error.
![Frozen_graph_eror](https://user-images.githubusercontent.com/34171201/77584161-58b86380-6eb0-11ea-8de0-770dc3d419b2.JPG)
