### ISSUE TITLE
validaton_data syntax error

### ISSUE THREAD

**Issue by sfarahaninia73** [qubvel/segmentation_models#102]
Hi, I'm running the code below, from the validation data
from segmentation_models import Unet, Linknet, FPN, PSPNet
from segmentation_models.backbones import get_preprocessing
from segmentation_models.losses import bce_jaccard_loss
from segmentation_models.metrics import iou_score
import os
import numpy as np
from skimage.color import gray2rgb
from skimage.io import imread, imsave
from skimage.transform import resize
from keras.preprocessing import image

model = Unet(
             'resnet34',
             input_shape=(256, 256, 1),
             encoder_weights=None,
             activation='sigmoid',
             classes=1
             )

model.compile(
              optimizer = 'adam',
              loss = 'binary_crossentropy',
              metrics = ['accuracy']
 )

model.summary()
# fit model
model.fit(
          x,
          y,
          batch_size = 10,
          epochs = 5
          validation_data=(x1, y1)
          )

 File "<ipython-input-17-a6b37935656c>", line 35
    validation_data=(x1, y1)
                  ^
SyntaxError: invalid syntax

**Comment by qubvel** [comment]
Hi @sfarahaninia73 
This is not a problem to create an issue. Syntax error means that you make a **syntax** mistake in the code. 
Try to improve your Python skills. 

P.S. You forgot a comma
```python
model.fit(
    x,
    y,
    batch_size = 10,
    epochs = 5,  # <- here
    validation_data=(x1, y1)
)
```
