### ISSUE TITLE
how to convert grayscale to 3 channel image

### ISSUE THREAD

**Issue by rnozhgan73** [qubvel/segmentation_models#104]
I prepared the following code based on the course tutorials to use imagenet for retrain but have error thank you for helping me

import keras
import glob
import cv2
import numpy as np
from matplotlib import pyplot as plt
import time
import keras.callbacks as cb
import keras.backend as k
from keras.preprocessing import image
#==============================================================================
#Functions
#==============================================================================
def database(data_list):
    y = np.zeros([np.size(data_list), 256, 256, 3])
    j = 0
    for i in data_list:
        img = image.load_img(i, target_size=(256, 256), grayscale=True)
        img = np.resize(img, (256, 256, 3))
        x = image.img_to_array(img)
        x = np.expand_dims(x, axis=0)
        x = x / 255.
        y[j,...] = x
        j = j + 1
    return y
     

train_images = glob.glob('./train/images/1/' + '*.png')
train_masks = glob.glob('./train/masks/' + '*.png')
val_images=glob.glob('./val/images/1/' + '*.png')
val_masks=glob.glob('./val/masks/' + '*.png')

x = database(np.sort(train_images))
y = database(np.sort(train_masks))
x1 = database(np.sort(val_images))
y1 = database(np.sort(val_masks))

print(x.shape, y.shape)
print(x1.shape, y1.shape)

###############
from segmentation_models import Unet, Linknet, FPN, PSPNet
from segmentation_models.backbones import get_preprocessing
from segmentation_models.losses import bce_jaccard_loss
from segmentation_models.metrics import iou_score
import os
import numpy as np
from skimage.color import gray2rgb
from skimage.io import imread, imsave
from skimage.transform import resize
from keras.preprocessing import image
from keras.layers import Input, Conv2D
from keras.models import Model

base_model  = Unet(
             'resnet34',
             encoder_weights='imagenet',
             activation='sigmoid',
             classes=1
             )
inp = Input(shape=(256, 256, 3))
l1 = Conv2D(3, (1, 1))(inp)
out = base_model (l1)
model = Model(inp, out, name=base_model.name)

model.compile(
              optimizer = 'adam',
              loss = 'binary_crossentropy',
              metrics = ['accuracy']
 )

model.summary()
# fit model
model.fit(
          x,
          y,
          batch_size = 10,
          epochs = 5,
          validation_data=(x1, y1),
          )

--------------
ValueError                                Traceback (most recent call last)
<ipython-input-30-5cc91c59655d> in <module>()
     40           batch_size = 10,
     41           epochs = 5,
---> 42           validation_data=(x1, y1),
     43           )
     44 

2 frames
/usr/local/lib/python3.6/dist-packages/keras/engine/training_utils.py in standardize_input_data(data, names, shapes, check_batch_axis, exception_prefix)
    136                             ': expected ' + names[i] + ' to have shape ' +
    137                             str(shape) + ' but got array with shape ' +
--> 138                             str(data_shape))
    139     return data
    140 

ValueError: Error when checking target: expected sigmoid to have shape (None, None, 1) but got array with shape (256, 256, 3)

**Comment by qubvel** [comment]
Hi @rnozhgan73 
> ValueError: Error when checking target: expected sigmoid to have shape (None, None, 1) but got array with shape (256, 256, 3)
Error is in output dimension (look at message, it is about target)
So may be you load your mask not as binary but as 3 channels image.

**Comment by rnozhgan73** [comment]
hi @qubvel 
Thanks for the guide
My problem has been resolved.
