### ISSUE TITLE
Question regarding label/groundtruth data

### ISSUE THREAD

**Issue by S4WRXTTCS** [qubvel/segmentation_models#108]
It's my understanding that the label/groundtruth data has to be represented by floating point values. 

Is that correct? Is it a float16 or the default 8 byte floating point value that Python has?

I'm asking because I'm trying to train a segmentation model that has 8 classes, and 603 images. I have 32GB of memory in my machine so I should be able to train this without issues, but I'm running out of memory. I believe what's happening is the groundtruth data is getting converted to 8 byte floating point values.  So it explodes the memory usage. 

Attached is my code. This code seems to work fine for two classes, but when I expanded it to 8 classes I ran into memory issues before it trains. 

[seg_train.zip](https://github.com/qubvel/segmentation_models/files/3214613/seg_train.zip)

**Comment by qubvel** [comment]
Hi @S4WRXTTCS 
May be after resizing masks became `float`. But for training it is ok to have masks as 'uint8' data.
If you have memory issues try to write `data_generator` for loading data on demand and use `model.fit_generator`.

**Comment by S4WRXTTCS** [comment]
I wasn't able to use 'uint8' for the masks. For some reason I got really bad training results when I used that. I ended up setting the data to uint8, and the masks to float32. That reduced the memory usage quite a bit from what it was, and got equal results to what I had before.
