### ISSUE TITLE
How to assign class_weights for  5 classes?

### ISSUE THREAD

**Issue by blaxe05** [qubvel/segmentation_models#109]
Hope you can show an example on how to assign class_weights for each class in loss function.
I tried with class_weights = [1,10,50,10,50] its return error due to tensor shape. My data is one-hot-encoded for all 5 classes. I am trying to use the PSPNet with class_weights.

**Comment by qubvel** [comment]
Hi @blaxe05 
Please, provide full error trace and a simple code snippet if possible. Thanks.

**Comment by dou3516** [comment]
Include background in weight may works.

**Comment by lewlin** [comment]
I also have issues in using class weights. I define my custom loss using a closure as:

```
def my_loss(class_weights):  
    def closure(gt, pr):
        return sm.losses.cce_jaccard_loss(gt, pr, class_weights=class_weights)
    return closure
```

then compile model with (I have 6 classes).

`model.compile('Adam', loss = my_loss([1., 1., 1., 1., 1., 1.])`

but I get:

```
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
~/miniconda3/envs/dev3-tf/lib/python3.7/site-packages/tensorflow/python/framework/ops.py in _create_c_op(graph, node_def, inputs, control_inputs)
   1658   try:
-> 1659     c_op = c_api.TF_FinishOperation(op_desc)
   1660   except errors.InvalidArgumentError as e:

InvalidArgumentError: Dimensions must be equal, but are 256 and 6 for 'loss/sigmoid_loss/mul_1' (op: 'Mul') with input shapes: [?,256,256], [6].
```
I am happy to post more code / debug info but I think it would help if you could post an example snippet of how to use class weights.

**Comment by qubvel** [comment]
Hi, @lewlin 
How did you define your model? it seems that your output data or target tensor have wrong dimensions

**Comment by lewlin** [comment]
Model is defined as:

```
    model = sm.Unet(
            backbone='resnet34`,
            input_shape=(256, 256, 3),
            encoder_weights='imagenet',
            classes=6,
            )
```

my number of classes is 6 and is equal to number of channels in output labels. @qubvel : do I do something wrong?

BTW, regarding my previous comment: it seems that using closure for custom loss is a bad idea as it yields issues in saving/loading model history :(

**Comment by qubvel** [comment]
Looks correct, did it work without class weights?

**Comment by lewlin** [comment]
Yes works w/o class weights (eg `class_weights=1.`) but not with class weight. I have a busy weekend but will go through code next week and will solve the mystery. Please don't close issue.

**Comment by jovahe** [comment]
@lewlin Has the problem been solved? I had the same problem.

**Comment by lewlin** [comment]
The busy weekend has become a busy week :-) I _will_ solve this, I just need the problem to become annoyingly critical (right now is just annoying).

**Comment by moritzmoritz98** [comment]
For myself the code seems at that position faulty too:
https://github.com/qubvel/segmentation_models/blob/ef6350388a0e774b8e602268c8f6a90ac0ed3a29/segmentation_models/losses.py#L77
since `categorical_crossentropy` does average about the last axis, so that class weights have to be applied before calculating CE (or propably within):
`- tf.reduce_sum(target * tf.log(output), -1)` ( https://github.com/keras-team/keras/blob/b810de658d022c38ce14e49693e6cb45d024333a/keras/backend/tensorflow_backend.py#L3564 )

**Comment by jovahe** [comment]
I define a customer loss function as follow,
def self_define_loss(customer_loss, class_weights):
    r"""sum loss with customer class_weight:
        ..
        Args:
            customer_loss: customer loss, such as: jaccard_loss, bce_jaccard_loss, cce_jaccard_loss, dice_loss, bce_dice_loss,cce_dice_loss
            class_weights: 1. or list of class weights for jaccard loss, len(weights) = C

        Returns:
            loss
        """
    if len(class_weights) == 0:
        class_weights = 1.
    def closure(gt, pr):
        tt = globals().get('%s' % customer_loss)
        # print("func:{}".format(tt))
        return tt(gt, pr, class_weights=class_weights)
    return closure
However, when I load the trained model,
model = load_model(config.model_path, custom_objects={'self_define_loss':self_define_loss})
 I got a error as follow:
ValueError: Unknown loss function:closure
How can I load model correctly?

**Comment by jovahe** [comment]
I define a customer loss function as follow,
`def self_define_loss(customer_loss, class_weights):
    r"""sum loss with customer class_weight:
        ..

        Args:
            customer_loss: customer loss, such as: jaccard_loss, bce_jaccard_loss, cce_jaccard_loss, dice_loss, bce_dice_loss,cce_dice_loss
            class_weights: 1. or list of class weights for jaccard loss, len(weights) = C

        Returns:
            loss

        """
    if len(class_weights) == 0:
        class_weights = 1.

    def closure(gt, pr):
        tt = globals().get('%s' % customer_loss)
        # print("func:{}".format(tt))
        return tt(gt, pr, class_weights=class_weights)

    return closure`
However, when I load the trained model,
model = load_model(config.model_path, custom_objects={'self_define_loss':self_define_loss})
I got a error as follow:
ValueError: Unknown loss function:closure
How can I load model correctly?

**Comment by jovahe** [comment]
I define a customer loss function as follow,
`def self_define_loss(customer_loss, class_weights):
    if len(class_weights) == 0:
        class_weights = 1.

    def closure(gt, pr):
        tt = globals().get('%s' % customer_loss)
        # print("func:{}".format(tt))
        return tt(gt, pr, class_weights=class_weights)

    return closure`
However, when I load the trained model,
model = load_model(config.model_path, custom_objects={'self_define_loss':self_define_loss})
I got a error as follow:
ValueError: Unknown loss function:closure
How can I load model correctly?

**Comment by jovahe** [comment]
I define a customer loss function as follow,

def self_define_loss(customer_loss, class_weights):
    if len(class_weights) == 0:
        class_weights = 1.
    def closure(gt, pr):
        tt = globals().get('%s' % customer_loss)
        # print("func:{}".format(tt))
        return tt(gt, pr, class_weights=class_weights)
    return closure

However, when I load the trained model,
model = load_model(config.model_path, custom_objects={'self_define_loss':self_define_loss})
I got a error as follow:
ValueError: Unknown loss function:closure
How can I load model correctly?

**Comment by jovahe** [comment]
I define a customer loss function as follow,
`def self_define_loss(customer_loss, class_weights):
    if len(class_weights) == 0:
        class_weights = 1.
    def closure(gt, pr):
        tt = globals().get('%s' % customer_loss)
        # print("func:{}".format(tt))
        return tt(gt, pr, class_weights=class_weights)
    return closure`
However, when I load the trained model,
model = load_model(config.model_path, custom_objects={'self_define_loss':self_define_loss})
I got a error as follow:
ValueError: Unknown loss function:closure
How can I load model correctly?

**Comment by jovahe** [comment]
I define a customer loss function as follow,
def self_define_loss(customer_loss, class_weights):
    def closure(gt, pr):
        tt = globals().get('%s' % customer_loss)
        # print("func:{}".format(tt))
        return tt(gt, pr, class_weights=class_weights)
    return closure

However, when I load the trained model,
model = load_model(config.model_path, custom_objects={'self_define_loss':self_define_loss})
I got a error as follow:
ValueError: Unknown loss function:closure
How can I load model correctly?

**Comment by jovahe** [comment]
I define a customer loss function as follow,
`I define a customer loss function as follow,

def self_define_loss(customer_loss, class_weights):
    if len(class_weights) == 0:
        class_weights = 1.
    def closure(gt, pr):
        tt = globals().get('%s' % customer_loss)
        # print("func:{}".format(tt))
        return tt(gt, pr, class_weights=class_weights)
    return closure

However, when I load the trained model,
model = load_model(config.model_path, custom_objects={'self_define_loss':self_define_loss})
I got a error as follow:
ValueError: Unknown loss function:closure
How can I load model correctly?`

However, when I load the trained model,
model = load_model(config.model_path, custom_objects={'self_define_loss':self_define_loss})
I got a error as follow:
ValueError: Unknown loss function:closure
How can I load model correctly?

**Comment by jovahe** [comment]
I define a customer loss function as follow,
`def self_define_loss(customer_loss, class_weights):
    def closure(gt, pr):
        tt = globals().get('%s' % customer_loss)
        # print("func:{}".format(tt))
        return tt(gt, pr, class_weights=class_weights)

    return closure`
However, when I load the trained model,
model = load_model(config.model_path, custom_objects={'self_define_loss':self_define_loss})
I got a error as follow:
ValueError: Unknown loss function:closure
How can I load model correctly?

**Comment by qubvel** [comment]
@jovahe
You can pass `custom_objects` or use `compile=False` while loading

**Comment by jovahe** [comment]
Thansk a lot, I have fix my problem according to your suggestion.

**Comment by jovahe** [comment]
@qubvel Thansk a lot, I have fix my problem according to your suggestion.

**Comment by love6tao** [comment]
> For myself the code seems at that position faulty too:
> https://github.com/qubvel/segmentation_models/blob/ef6350388a0e774b8e602268c8f6a90ac0ed3a29/segmentation_models/losses.py#L77
> 
> 
> since `categorical_crossentropy` does average about the last axis, so that class weights have to be applied before calculating CE (or propably within):
> `- tf.reduce_sum(target * tf.log(output), -1)` ( https://github.com/keras-team/keras/blob/b810de658d022c38ce14e49693e6cb45d024333a/keras/backend/tensorflow_backend.py#L3564 )

so, how to solve this problem?

**Comment by qubvel** [comment]
try to install:
```bash
$ pip install https://github.com/qubvel/segmentation_models@fix/losses-class-weights
```
This should fix the problem, but I did not test it yet.

**Comment by love6tao** [comment]
> try to install:
> 
> ```shell
> $ pip install https://github.com/qubvel/segmentation_models@fix/losses-class-weights
> ```
> 
> This should fix the problem, but I did not test it yet.

 HTTP error 404 while getting https://github.com/qubvel/segmentation_models@fix/losses-class-weights
  Could not install requirement https://github.com/qubvel/segmentation_models@fix/losses-class-weights because of error 404 Client Error: Not Found for url: https://github.com/qubvel/segmentation_models@fix/losses-class-weights
Could not install requirement https://github.com/qubvel/segmentation_models@fix/losses-class-weights because of HTTP error 404 Client Error: Not Found for url: https://github.com/qubvel/segmentation_models@fix/losses-class-weights for URL https://github.com/qubvel/segmentation_models@fix/losses-class-weights

**Comment by love6tao** [comment]
> try to install:
> 
> ```shell
> $ pip install https://github.com/qubvel/segmentation_models@fix/losses-class-weights
> ```
> 
> This should fix the problem, but I did not test it yet.

I  applied the following loss function, and after replacing the loss function described above, the network can start training. . .

def pixel_wise_cross_entropy_loss_weighted(logits, labels, class_weights):
    '''
    Weighted cross entropy loss, with a weight per class
    :param logits: Network output before softmax
    :param labels: Ground truth masks
    :param class_weights: A list of the weights for each class
    :return: weighted cross entropy loss
    '''
    n_class = len(class_weights)
    flat_logits = tf.reshape(logits, [-1, n_class])
    flat_labels = tf.reshape(labels, [-1, n_class])
    class_weights = tf.constant(np.array(class_weights, dtype=np.float32))
    weight_map = tf.multiply(flat_labels, class_weights)
    weight_map = tf.reduce_sum(weight_map, axis=1)
    loss_map = tf.nn.softmax_cross_entropy_with_logits_v2(logits=flat_logits, labels=flat_labels)
    weighted_loss = tf.multiply(loss_map, weight_map)
    loss = tf.reduce_mean(weighted_loss)
    return loss

**Comment by qubvel** [comment]
@love6tao forgot `git+`, edited

**Comment by love6tao** [comment]
> @love6tao forgot `git+`, edited
the new _categorical_crossentropy is ok 
Thank you, qubvel, this problem is solved
