### ISSUE TITLE
How to make PSPNet support (None,None,3) input_shape?

### ISSUE THREAD

**Issue by liminn** [qubvel/segmentation_models#112]
I mentioned that the annotation in PSPNet:
```
 input_shape: shape of input data/image ``(H, W, C)``.
            ``H`` and ``W`` should be divisible by ``6 * downsample_factor`` and **NOT** ``None``!
```
But FPN support (None,None,3) input_shape:
```
input_shape: shape of input data/image ``(H, W, C)``, in general
                case you do not need to set ``H`` and ``W`` shapes, just pass ``(None, None, C)`` to make your model be
                able to process images af any size, but ``H`` and ``W`` of input images should be divisible by factor ``32``
```

**Because I want to predict image with arbitrary shape.** 
What can i do to make PSPNet support (None,None,3) input_shape?

**Comment by qubvel** [comment]
Hi @liminn 
I did not find a way to do it within an easy way, on the other hand, PSP module is not fully conv (it has kind of pooling operation) so you have to provide the same shape during training/validation/test. In another case you may have unexpected results.
