### ISSUE TITLE
Unable to get good results with categorical_crossentropy on a Multi-Class Object Segmentation Model

### ISSUE THREAD

**Issue by S4WRXTTCS** [qubvel/segmentation_models#115]
My goal is to train a Multi-Class FPN based Object segmentation network consisting of 8 or more classes. As I understand it the categorical_crossentropy model compile option should be used for that, but I can't seem to get it to work on a 2-class test case.

I can get good results with a 2-class FPN Object Segmentation network when I use
binary_crossentropy, and binary accuracy for the Model Compile. 

It seems like I'm missing something obvious. 

Here is my code
[Code.zip](https://github.com/qubvel/segmentation_models/files/3238536/Code.zip)

Here is a Results comparison between binary_crossentropy and categorical_crossentropy. 
[Result_Comparison.zip](https://github.com/qubvel/segmentation_models/files/3238538/Result_Comparison.zip)

**Comment by rakhecha42** [comment]
same

**Comment by qubvel** [comment]
What is your activation function? for categorical it should be `softmax` and for binary `sigmoid`

**Comment by S4WRXTTCS** [comment]
For the categorical_crossentropy option I use softmax.
For the binary_crossentropy I use sigmoid.

Is it possible that I don't have my dataset correctly configured for categorical_crossentropy?

Here is my dataset for the two-classes. 
https://drive.google.com/open?id=1cuiXlbmRQ-iyfD8lzfnMgrG4M4LwJSCW

Now I did test out more classes, and binary_crossentropy worked fine even when I reached all 8-classes that my original dataset has.

**Comment by S4WRXTTCS** [comment]
I updated my code to switch from floating point for the mask to uint8 with values of {0, 1}.

It still doesn't work using categorical_crossentropy. So I still either have the dataset wrongly configured or my understanding of how it's supposed to work is wrong. Maybe I need to add a background layer. Something that doesn't seem to be required for binary_crossentropy. 

[The_Two.zip](https://github.com/qubvel/segmentation_models/files/3283483/The_Two.zip)

**Comment by qubvel** [comment]
Background is necessary for categorical_crossentropy 
Make sure if your sum onehot encoded mask across last dim you will have np.ones() array.

**Comment by S4WRXTTCS** [comment]
Adding the background fixed it so now I'm getting the expected results.

Thanks for your help.

Here is the code in case anyone else is playing around with Object Segmentation on a dataset that consist of only a single object class per image. So all I did to add the background mask was to simply invert the object mask for each image, and assign it to background mask. 

[Code.zip](https://github.com/qubvel/segmentation_models/files/3288422/Code.zip)

**Comment by ruchika61** [comment]
> My goal is to train a Multi-Class FPN based Object segmentation network consisting of 8 or more classes. As I understand it the categorical_crossentropy model compile option should be used for that, but I can't seem to get it to work on a 2-class test case.
> 
> I can get good results with a 2-class FPN Object Segmentation network when I use
> binary_crossentropy, and binary accuracy for the Model Compile.
> 
> It seems like I'm missing something obvious.
> 
> Here is my code
> [Code.zip](https://github.com/qubvel/segmentation_models/files/3238536/Code.zip)
> 
> Here is a Results comparison between binary_crossentropy and categorical_crossentropy.
> [Result_Comparison.zip](https://github.com/qubvel/segmentation_models/files/3238538/Result_Comparison.zip)

hi
@S4WRXTTCS, can you provide codes for multi-class object segmentation you designed for your 8 classes.
Also suggest way to generate custom dataset mask generation, that looks similar to camvid dataset.
it will  be thankful to you.
