### ISSUE TITLE
PSPNet and ResNet blocks

### ISSUE THREAD

**Issue by tinalegre** [qubvel/segmentation_models#119]
Dear all
I am trying to train a PSPNet using Resnet50 as backbone:
```
# define model with output of N classes, where N > 1
model = PSPNet(backbone_name='resnet50', input_shape=(256, 256, 3), encoder_weights=None, downsample_factor=4, classes=N, activation='softmax')
```
Depending on the [downsample_factor](https://github.com/qubvel/segmentation_models/blob/e948860ba6e6c8e6bdd8638e52374cef3df266e8/segmentation_models/pspnet/model.py#L102) value a specific ResNet layer is selected over which the pyramid-pooling is computed, e.g. for `resnet50` and `downsample_factor=4`, it would be the [stage2_unit1_relu1](https://github.com/qubvel/segmentation_models/blob/e948860ba6e6c8e6bdd8638e52374cef3df266e8/segmentation_models/pspnet/model.py#L11) layer. When I [plot my model](https://imgur.com/a/26NVDyZ), I see however in the model only the ResNet layers as of `stage2_unit1_relu1` and all the previous Resnet layers are not shown/seem to be gone. Is this a problem of the visualization only? I would just really want to be sure, that the whole ResNet50 backbone is used and not only part of it. Also, from what I understand, this is guaranteed by:
https://github.com/qubvel/segmentation_models/blob/e948860ba6e6c8e6bdd8638e52374cef3df266e8/segmentation_models/pspnet/builder.py#L34
in which we use as input for the PSPNet, the whole ResNet backbone as input tensor, right? Is my description correct about what's exactly happening? I was expecting to see, instead of:
https://github.com/qubvel/segmentation_models/blob/e948860ba6e6c8e6bdd8638e52374cef3df266e8/segmentation_models/pspnet/builder.py#L36
something like:
      `x = extract_outputs(backbone, [from_first_backone_layer:psp_layer])[0]`

**Comment by qubvel** [comment]
Hi @tinalegre 
Psp module is computed over 'stage2_unit1_relu1' and all other stages (stage3, stage4) are gone. to use more resnet layers use higher downsample factor (e.g. 8 or 16).

**Comment by tinalegre** [comment]
@qubvel thanks for the feedback
