### ISSUE TITLE
Improve readme

### ISSUE THREAD

**Issue by morenoh149** [qubvel/segmentation_models#12]
Hello,
I consider myself an ML Beginner, but I've been exposed to many ideas. I think the readme would be much better if there was a paragraph explaining some basic things about this package.

1. We can distribute pretrained model weights for segmentation models same as for object detection tasks with imagenet weights. `link to transfer learning blogpost`.
1. What considerations might go into reusing weights? would weights trained on astronomical data work for cell segmentation data? How about for radio signals in noise?
1. Explain term `Backbone model`, how can we use imagenet weights as the backbone for a segmentation task? why does this work?
1. Explain term `Preprocessing`, keras.io docs show nothing for `bcg` or `ka*`.

to a lesser extent, give the `Available Models` section more space in the readme. At first glance it seemed like the backbones are the primary concern when using this package, but the primary concern should probably be the toplevel architecture to try out (not the backbones).

If you approve I could draft up such a paragraph if you answer these questions.

**Comment by qubvel** [comment]
Hello @morenoh149, thanks for your interest and ideas!

As for preptrained backbones, this is really a key feature of this repository, so a lot of attention is paid to it. However, I absolutely agree that the description of the main architectures is also very important to add.

It would be great if you could help make this readme more clear and describe the ideas you listed. Thank you!

**Comment by morenoh149** [comment]
@qubvel lets start by having you answer each of my questions, or providing reading material that answers my questions.
