### ISSUE TITLE
Using 'efficientnetb0' as backbone is not available.

### ISSUE THREAD

**Issue by kevinkwshin** [qubvel/segmentation_models#122]
Thank you for sharing your models.
Today, I tried to use u-net with 'EfficientNet' as its classification performance looks good.
But I think, it is not updated, I've got error message below.

 
model = Unet('efficientnetb0',
             input_shape=(img_height, img_width, 3),
             encoder_weights='imagenet',
             classes=4) #13
             #activation='sigmoid')

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-84-c95862ca8326> in <module>
     12              input_shape=(img_height, img_width, 3),
     13              encoder_weights='imagenet',
---> 14              classes=4) #13
     15              #activation='sigmoid')
     16 

/usr/local/lib/python3.5/dist-packages/segmentation_models/utils.py in wrapper(*args, **kwargs)
     29                     kwargs[new_arg] = kwargs[old_arg]
     30 
---> 31             return func(*args, **kwargs)
     32 
     33         return wrapper

/usr/local/lib/python3.5/dist-packages/segmentation_models/unet/model.py in Unet(backbone_name, input_shape, classes, activation, encoder_weights, encoder_freeze, encoder_features, decoder_block_type, decoder_filters, decoder_use_batchnorm, **kwargs)
     61                             input_tensor=None,
     62                             weights=encoder_weights,
---> 63                             include_top=False)
     64 
     65     if encoder_features == 'default':

/usr/local/lib/python3.5/dist-packages/segmentation_models/backbones/__init__.py in get_backbone(name, *args, **kwargs)
     73 
     74 def get_backbone(name, *args, **kwargs):
---> 75     return Classifiers.get_classifier(name)(*args, **kwargs)
     76 
     77 

/usr/local/lib/python3.5/dist-packages/classification_models/__init__.py in get_classifier(cls, name)
     84     @classmethod
     85     def get_classifier(cls, name):
---> 86         return cls._models.get(name)[0]
     87 
     88     @classmethod

TypeError: 'NoneType' object is not subscriptable

**Comment by qubvel** [comment]
please use 
```bash
$ pip install -U git+https://github.com/qubvel/segmentation_models
```
