### ISSUE TITLE
Train backbone

### ISSUE THREAD

**Issue by makemate** [qubvel/segmentation_models#124]
Hi! Is it possible to load the pretrained backbone on ImageNet, train the backbone (e.g. DenseNet) on a task that is more similar to my specific problem and include the finetuned backbone then in U-Net? Thanks!

**Comment by qubvel** [comment]
Hi @makemate 
It is not supported out of the box, but it can be easily done manually.
1. Train backbone
2. Transfer weights
```python
def transfer_weights(trained_bacbone, unet_model):
    for i, layer in enumerate(trained_bacbone.layers):
        weights = layer.get_weights()
        unet_model.layers[i].set_weights(weights)
```

**Comment by makemate** [comment]
@qubvel Thanks for the feedback, I will try it out.
