### ISSUE TITLE
Black predictions for segmentation models

### ISSUE THREAD

**Issue by Anjali-Poornima666** [qubvel/segmentation_models#126]
I have trained segmentation model for UNET with 'resnet34' backbone. I got a very good accuracy for both validation and train sets. But when I'm trying make predictions using the trained model, I'm getting a black image. Could you please help me in this regards.

**Comment by qubvel** [comment]
Hi @Anjali-Poornima666 
I can not guess what went wrong. My be some mistake in data processioning.

**Comment by S4WRXTTCS** [comment]
How are you processing the mask = model.predict(test_image) output?  Are you simply multiplying it by 255, and saving the uint8 array as a monochrome image for each class layer? Where the test image is included within the training data?
