### ISSUE TITLE
Run code

### ISSUE THREAD

**Issue by arash1409** [qubvel/segmentation_models#127]
how to run this code?
Can we use ground-truth images images to segment this code?

**Comment by qubvel** [comment]
Hi @arash1409 
Look at README, there is an example

**Comment by arash1409** [comment]
how to run res file?

**Comment by arash1409** [comment]
> Hi @arash1409
> Look at README, there is an example

how to run rst file?

**Comment by qubvel** [comment]
This repo provide models, you have to create training pipeline by yourself. There is an example how to write a simple pipeline, by it is not complete. Take some courses and read tutorials about python/deep-learining/keras.
