### ISSUE TITLE
RGB D pretrained

### ISSUE THREAD

**Issue by johanneskpp** [qubvel/segmentation_models#136]
When I change the input shape to (None, None, 4) for RGB-D Images is it still possible to use the pretrained model (imagenet) because the pretraining with imagenet uses normal RGB images?

**Comment by qubvel** [comment]
Hi, yes it is possible, please, read the docs next time) 
https://segmentation-models.readthedocs.io/en/latest/tutorial.html#training-with-non-rgb-data
