### ISSUE TITLE
Problem inpute shape

### ISSUE THREAD

**Issue by xor0x** [qubvel/segmentation_models#138]
Hello please help i get this message.
ValueError: Error when checking input: expected input_1 to have 4 dimensions, but got array with shape (512, 512)

**Comment by qubvel** [comment]
Read the error and chech the dimensions of input image)

**Comment by xor0x** [comment]
it is my input and model 
# define model
model = Unet(backbone_name=BACKBONE, encoder_weights=None, input_shape=(512, 512, 1), classes=1)
model.compile('Adam', loss=bce_jaccard_loss, metrics=[iou_score])


# fit model
# if you use data generator use model.fit_generator(...) instead of model.fit(...)
# more about `fit_generator` here: https://keras.io/models/sequential/#fit_generator
model.fit(
    x=x_train,
    y=y_train,
    batch_size=1,
    epochs=100,
    validation_data=(x_val, y_val),
)

**Comment by Dendrophylax** [comment]
Keras probably expect (512, 512, 1) instead of (512, 512). You can do y_train=y_train[:,:,np.newaxis] or use expand_dims().

**Comment by qubvel** [comment]
Model expect to have 4d input: (batch_size, height, width, channels) -> e.g. (1, 512, 512, 1).
Use `x = x[None, ..., None] ` to convert (512, 512) -> (1, 512, 512, 1).

**Comment by xor0x** [comment]
after convert i have new error
IndexError: index 512 is out of bounds for axis 0 with size 512
