### ISSUE TITLE
Problem in data loading.

### ISSUE THREAD

**Issue by harsh52** [qubvel/segmentation_models#139]
Hello there,

I am not sure how to load data in `x_train, y_train, x_val, y_val = load_data(...)`
i have file structure like this:
 

>       /data
>     /train
>         /images
>             1.png
>             2.png
>             ...
>         /masks
>             1.tif
>             2.tif
>     /val
>         /images
>             ...
>         /masks
>             ...

details about dataset:

my each mask(.tif) format contains five masks which corresponds to five classes in a train image.
and my each image contains five classes in it's.
so basically i need to segment five classes in an image.
any type of help would be very helpful 
Thank you.

**Comment by qubvel** [comment]
Look through closed issues, there were such questions
You also need to make on-hot encoding for classes
