### ISSUE TITLE
input shape

### ISSUE THREAD

**Issue by abensaid** [qubvel/segmentation_models#14]
Hi
Can you provide us with a simple example of unet (or fpn ...).
I couldn't figure out how to build the model and specify my input data.
How should I shape my data? I tried x32 for H and W but it's not working

**Comment by qubvel** [comment]
Hi, @abensaid 

```python
import numpy as np
from segmentation_models import Unet

model = Unet('inceptionv3', input_shape=(None, None, 3))

inp = np.ones((1, 32, 32, 3))
out = model.predict(inp)
```
Does the following code works for you?

**Comment by abensaid** [comment]
I am trying to fit my data of the shape (n_sample,128,128,1). This is the error i get:
ValueError: Error when checking input: expected data to have shape (None, None, 3) but got array with shape (128, 128, 1)

**Comment by qubvel** [comment]
You have to provide image with 3 channels not 1. In your case it should be (128, 128, 3) not (128, 128, 1).
