### ISSUE TITLE
Moving to tf.keras 

### ISSUE THREAD

**Issue by bonlime** [qubvel/segmentation_models#140]
Hi. First of all thanks for your repo!
Have you considered moving to `tf.keras` instead of using separate `keras`? It would make your repo compatible with new TF 2.0 out of the box while still being compatible with older versions of TF as well.

**Comment by qubvel** [comment]
Hi @bonlime 
Yes, I have such plans, I think it should be done in a way of keras-applications with possibility to define your framework (`keras` or `tf.keras`). I did not still move to `tf.keras` by myself, so cannot guarantee this process will be fast.

Next week I am going to start adopting `classification-models` to make this possible. Any advices, bug reports, testing, PRs from community are appreciated.

**Comment by bonlime** [comment]
@qubvel 
I'm working on moving to tf.keras on my own branch but there is an issue. In order to make it work you also have to move image-classifiers and efficient net to TF Keras. Right now I'm able to load models with backbones defined in this repo: `inceptionresnetv2, inceptionv3, resnext50, resnext101, mobilenet, mobilenetv2`. For other backbones I get an error `object has no attribute 'outbound_nodes'` which appears due to mixing of keras and tf.keras

**Comment by bonlime** [comment]
There would be no change in public API. The only things I had to slightly change are: 
1. `conv_utils` is now at `tensorflow.python.keras.utils.conv_utils`. I don't know if it's a good practice to use `python.keras`  
2. there is no such thing as `interfaces.legacy_upsampling2d_support` in `tf.keras`

**Comment by qubvel** [comment]
Hi @bonlime @lc0 @NiklasDL @chAwater @srikrishna0130 @northanapon @Tyler-D 

I have prepared a lib update to work together with keras and tf.keras and need your help!
If someone have a time to test it and give a feedback it would be great (autotests have been passed)!

Some words about update:
1) API almost the same (moved `get_preprocessing` to root)
```python
import segmentation_models as  sm

model = sm.Unet('resnet18')
preprocess_input = sm.get_preprocessing('resnet18')
```
2) Choose your framework:
a) If you have `Keras` installed -> lib will load with `Keras`, if not lib will load with `tf.keras`
b) You can setup env var `SM_FRAMEWORK="keras"`/`SM_FRAMEWORK="tf.keras"` before import segmentation_models
c) You can change framework in runtime 
```python
>>> import segmentation_models as sm
Segmentation models: using `keras` framework.
>>> sm.framework() 
'keras'
>>> sm.set_framework('tf.keras`)
>>> sm.framework() 
'tf.keras'
```
3) I have removed almost all custom objects, so now trained models (except efficientnets) can be loaded without importing segmentation moldes lib.
4) You also can change `image_data_format`  (may be useful to convert models (#69 ))
```python
keras.set_image_data_format('channels_first`)
```

### Installation
Now you can install it 
```bash
$ pip install -U git+https://github.com/qubvel/segmentation_models@feature/tf.keras \
                        git+https://github.com/qubvel/classification_models@feature/tf.keras \
                        git+https://github.com/qubvel/efficientnet
```

Roll back:
```bash
pip install -U segmentation-models==0.2.1
```
Waiting for your feedback, thank you!

**Comment by NiklasDL** [comment]
Hi @qubvel, these are great news. I will definitely try out the tf2.0 tf.keras implementation and provide some feedback (will take some time, my data sets are huge).

**Comment by Tyler-D** [comment]
Hi @qubvel , will check it.

**Comment by bonlime** [comment]
Hi @qubvel . I've checked Classification Models and Segmentation models everything works fine except `get_preprocessing`. [Here](https://github.com/qubvel/segmentation_models/blob/a29728e10c11c122ba1a39ee70a72fe53026a89a/segmentation_models/__init__.py#L98) you try to inject global submodules into it which is unnecessary.  
upd. Also now global losses from keras are separated from losses in segmentation models. Before it was possible to write `from segmentation_models.losses import binary_crossentropy` and now bce is available only inside decorated functions. I personally don't see it as an issue and think it's totally fine

**Comment by bonlime** [comment]
A possible solution for the problem with get_preprocessing:
```python
from .backbones.backbones_factory import BackbonesFactory
class InjectedBackbones(BackbonesFactory):
    @staticmethod
    def get_kwargs():
        return {
            'backend': _KERAS_BACKEND,
            'layers': _KERAS_LAYERS,
            'models': _KERAS_MODELS,
            'utils': _KERAS_UTILS,
        }
get_preprocessing = InjectedBackbones().get_preprocessing
```

**Comment by qubvel** [comment]
@bonlime thanks for pointing this out, fixed!

**Comment by deblauwetom** [comment]
Awesome, this works now! 

For reference, below is the error I got with tensorflow without your branch here:

`  File "/usr/local/lib/python3.7/site-packages/segmentation_models/backbones/__init__.py", line 75, in get_backbone
    return Classifiers.get_classifier(name)(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/classification_models/resnet/models.py", line 20, in classifier
    **model_params)
  File "/usr/local/lib/python3.7/site-packages/classification_models/resnet/builder.py", line 38, in build_resnet
    img_input = Input(shape=input_shape, name='data')
  File "/usr/local/lib/python3.7/site-packages/keras/engine/input_layer.py", line 178, in Input
    input_tensor=tensor)
  File "/usr/local/lib/python3.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/keras/engine/input_layer.py", line 87, in __init__
    name=self.name)
  File "/usr/local/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 517, in placeholder
    x = tf.placeholder(dtype, shape=shape, name=name)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py", line 2074, in placeholder
    raise RuntimeError("tf.placeholder() is not compatible with "
RuntimeError: tf.placeholder() is not compatible with eager execution.
`

**Comment by bonlime** [comment]
@qubvel  it appears the minimal supported TF version is going to be 1.13. When trying to instantiate a FPN model with TF 1.12 there is an error at line 
`layers.UpSampling2D((8, 8), interpolation='nearest', name='upsampling_stage5')(s5)` due to the fact that there is no `interpolation` parameter in TF 1.12 Upsampling

**Comment by qubvel** [comment]
@bonlime thanks, will note it in README

**Comment by northanapon** [comment]
@qubvel Thank you for the update on @feature/tf.keras.

As @bonlime mentioned, `get_preprocessing` does not work. I directly used `keras_applications`.

For the model part, I tried `Unet` on my small dataset using `vgg16` as a backend. I did not have `Keras` installed. The model worked on both `tensorflow==2.0.0-beta1` and `tensorflow-gpu==2.0.0-beta1`.

**Comment by qubvel** [comment]
Merged to master, PyPI:
```bash
$ pip install -U --pre segmentation-models
```

**Comment by netanelk12** [comment]
Hi @qubvel , 
i have used your repository for unet cnn like this:

from segmentation_models import Unet
 model = Unet(input_shape=(640, 960,3))
 smooth = 1.
 model.compile(optimizer=Adam(lr=1e-4),
              loss=dice_calc_loss, metrics=[dice_calc])

but when i train the model i get error of:

  "ResourceExhaustedError:  OOM when allocating tensor with shape[13,192,320,480] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[node decoder_stage3_concat_6/concat (defined at /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:3009) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
 [Op:__inference_keras_scratch_graph_124548]"

this is the way i train the model:
history=model.fit_generator(train_generator(image_generator,mask_generator),steps_per_epoch=63,epochs=100,callbacks=[model_checkpoint_callback])

i will be happy to get help

**Comment by NiklasDL** [comment]
@netanelk12 The error says that the batch does not fit into your GPU memory. What is the steps_per_epoch (batch size) in your generator? Your input size is very huge (input_shape=(640, 960,3)), therefore a small batch size is very likely necessary, even with a high end GPU.

**Comment by netanelk12** [comment]
> @netanelk12 The error says that the batch does not fit into your GPU memory. What is the steps_per_epoch (batch size) in your generator? Your input size is very huge (input_shape=(640, 960,3)), therefore a small batch size is very likely necessary, even with a high end GPU.

thank u very much its solved the problem!
one more question , how can i  run other classifiers as encoders for unet?, i don't know wich options i have, i have only seen 'resnet34' so far as a encoder
@qubvel

**Comment by netanelk12** [comment]
thank u very much ,its solve the problem!!! but now i have one more problem :

from segmentation_models import Unet
from segmentation_models.utils import set_trainable

 model = Unet(backbone_name='resnet34',input_shape=(640, 960,3), encoder_weights='imagenet', encoder_freeze=True)
    smooth = 1.
    model.compile(optimizer=Adam(lr=1e-4),
              loss=dice_calc_loss, metrics=[dice_calc])

model.fit_generator(train_generator(image_generator,mask_generator),steps_per_epoch=63,epochs=2,callbacks=[model_checkpoint_callback])

set_trainable(model)

model.fit_generator(train_generator(image_generator,mask_generator),steps_per_epoch=63,epochs=100,callbacks=[model_checkpoint_callback])

i got error:
/usr/local/lib/python3.6/dist-packages/segmentation_models/utils.py in set_trainable(model, recompile, **kwargs)
     34             loss_weights=model.loss_weights,
     35             sample_weight_mode=model.sample_weight_mode,
---> 36             weighted_metrics=model.weighted_metrics,
     37         )
     38 

AttributeError: 'Model' object has no attribute 'weighted_metrics'

@qubvel

**Comment by netanelk12** [comment]
even if  i use the matrics and the loss of your repository(before it was my loss function and my matrics) like this:

model = sm.Unet(backbone_name='resnet34',input_shape=(640, 960,3), encoder_weights='imagenet', encoder_freeze=True)
    smooth = 1.
    model.compile(
    'Adam',
    loss=sm.losses.bce_jaccard_loss,
    metrics=[sm.metrics.iou_score],
    )

its show me the same error

**Comment by nataliameira** [comment]
Has anyone found a solution for fine tuning?
