### ISSUE TITLE
How to correctly visualize a model with all layers?

### ISSUE THREAD

**Issue by sokadavi** [qubvel/segmentation_models#142]
When i try to visualize my model built with segmentation_models, i only get a minimum overview. 

Here is the source code:

```python
inp = Input(shape=(None, None, 4))
mapping_layer = Conv2D(3, (1, 1), kernel_initializer='he_uniform')(inp)
mapping_layer = BatchNormalization()(mapping_layer)

base_model = Unet(backbone_name=ENCODER_BACKBONE, input_shape=(None, None, 3), classes=1, activation='sigmoid',
                  encoder_weights='imagenet', encoder_freeze=True)
out = base_model(mapping_layer)
model = Model(inp, out, name=base_model.name)
```

And the output from keras.utils plot_model() function:

![model](https://user-images.githubusercontent.com/27925680/61306604-392f4e00-a7ed-11e9-919f-17ec39d25e0e.png)

Is there a way to visualize the Unet completely? 

Sorry if this is only an issue because i don't know enough basics!

**Comment by sokadavi** [comment]
I thought the solution might be setting the optional argument of tf.keras.utils.plot_model() function  "expand_nested" to True. But the output-plot was the same as shown above.

PS: expand_nested argument is only available in tf.keras.utils.plot_model(), but not in keras.utils.plot_model()

**Comment by qubvel** [comment]
Hi @sokadavi 
Dont know how to visualize the whole model, but you can extract and visualize u-resnet34 next way:
```python
uresnet34 = model.layers[-1] # or use your base_model
```

**Comment by qubvel** [comment]
This issue is more related to Keras repo
