### ISSUE TITLE
tf.keras: backbones: segmentation-models

### ISSUE THREAD

**Issue by qubvel** [qubvel/segmentation_models#148]
Adopt segmentation-models internal backbones to work with keras and tf.keras

**Comment by bfialkoff** [comment]
is this issue to deal with the fact that this is now broken? 
https://github.com/qubvel/segmentation_models/blob/b6e1d6524359ace0f9b9050f7523674c26026a4c/segmentation_models/backbones/__init__.py#L1

and should instead be `import efficientnet.keras as eff`

**Comment by qubvel** [comment]
it is not broken with pip package of efficientnet
this issue is related for adopting models for tf.keras
