### ISSUE TITLE
Preprocess input

### ISSUE THREAD

**Issue by avakanski** [qubvel/segmentation_models#156]
Hi everyone,
It is not very clear to me what the function imgs_train =  preprocess_input(imgs_train) does.
Does it depend on the used Backbone and does it differ across backbones?
I assume it does mean subtraction, but I am not sure what else it does.
And where the actual source code can be found?
Any explanation is appreciated, thank you,
Alex

**Comment by qubvel** [comment]
Hi @avakanski 
It depends on backbone, 
Different backbones have been trained with different preprocessing (see more in keras_applications.imagenet_utils file)

**Comment by avakanski** [comment]
Thank you Pavel for your reply. That helps.
And thanks for posting the library, it is very well prepared, and easy to use.
