### ISSUE TITLE
How to define Tensorflow as Backend?

### ISSUE THREAD

**Issue by ali-masoudi** [qubvel/segmentation_models#166]
How can define Tensorflow as Backend?
if I import optimizer from tf.keras I will get:ValueError: Could not interpret optimizer identifier (tf.keras)

but there is no problem with tf.keras, I am using it currently with other project and no problem.

**Comment by qubvel** [comment]
Hi, please, carefully read README and documentation first, than create issues, thanks.

**Comment by ali-masoudi** [comment]
oh just seen it
