### ISSUE TITLE
could you also provide a medical version of FPN/UNET

### ISSUE THREAD

**Issue by wenhuihuang1979** [qubvel/segmentation_models#169]
Medical version is only half parameters and good for training medical images, great if you could provide a medical version, thanks.

**Comment by qubvel** [comment]
Hi, don't have any idea what you are talking about. Please provide paper link or github repo for reference, thanks.

**Comment by wenhuihuang1979** [comment]
unet medical: https://github.com/NVIDIA/DeepLearningExamples/tree/master/TensorFlow/Segmentation/UNet_Medical
unet industrial:
https://github.com/NVIDIA/DeepLearningExamples/tree/master/TensorFlow/Segmentation/UNet_Industrial

thanks,

**Comment by qubvel** [comment]
Number of parameters you can choose by yourself changing backbone_name and decoder_channels parameters. 
No need to implement medical version from my point of view, they are almost the same.

**Comment by wenhuihuang1979** [comment]
okay, I see, Thanks, you can close this one. :)
