### ISSUE TITLE
How to do the segmentation task since the size of output is arbitrary? 

### ISSUE THREAD

**Issue by MaxKinny** [qubvel/segmentation_models#17]
Because the number of object of interest in a picture is arbitrary, the output size will be change with the input picture change. 

And the second question is that how to tell different regions corresponding to different entities/objects in the picture?

Thank you!

**Comment by qubvel** [comment]
Sorry, i`m not sure that understand you correctly, please describe your task more detailed. Is this task corresponds to PSPNet?

**Comment by MaxKinny** [comment]
> Sorry, i`m not sure that understand you correctly, please describe your task more detailed. Is this question corresponds to PSPNet?

I find that the function
```
model.predict(x)
```
will return a tensor with fixed size like axbxc which is a 3 dimension tensor where a , b and c are constant. However, I think the segmentation task will need the algorithm to produce the output(tensor) with different size. 

For example, when we do the face recognition task, you feed a picture with 3 persons in it, the output will be 3 bounding boxes that is a 2x4x3(where the first 2 means the coordinate, the second 4 means every bounding box consists of 4 vertexes and the last 3 means that there are 3 faces in the picture ) tensor. Next  time you feed a picture with 4 persons, the output should be a 2x4x4 tensor. 

As you can see, the output size is arbitrary, and I think the segmentation task should have the same property as the face recognition task.

**Comment by qubvel** [comment]
No, this is semantic segmentation task, a number of classes is predefined. To know more about semantic segmentation read papers of PSPNet or Unet. Another case is instance segmentation, where we want all objects, even of one class, have different masks. For this task try to find for example MaskRCNN.

**Comment by MaxKinny** [comment]
Oh，I see. Thank you！
