### ISSUE TITLE
Saved Model has no loss and optimizer

### ISSUE THREAD

**Issue by ali-masoudi** [qubvel/segmentation_models#172]
when I save the model and reload it, it has no optimizer and loss !?
Segmentation_models,Classification_modesl,Efficient_Net : all v1.0.0b1
what happens to them!

**Comment by qubvel** [comment]
Hi @ali-masoudi 
Losses and metrics are custom objects, you can pass them during model loading. I have remove them from auto-loading because now they have parameters, but AFAIK keras custom objects doesn`t serialize them, that can produce side effects.
