### ISSUE TITLE
The difference of model structures between version 1.* and 0.2.1 

### ISSUE THREAD

**Issue by aa1234241** [qubvel/segmentation_models#173]
Hello,
         Many thanks to your excellent project. 
         I want to know is there any model structure modification between different version.
         I once used the resnext101unet (version==0.2.1) for medical image segmentation.
         Now I update the version to 1.* and use the same resnext101unet structure and retrain the model using imagenet pretrained model.  However, I found that the new version model gets lower performance.
        Is there any structure changed from the old version? Should I redownload the pretrained Model?
         Sincerely

**Comment by qubvel** [comment]
Hi @aa1234241 
Thats strange:
1) ResNext models are the same architecture (tests have been passed, they produce same result)
2) Unet decoders also the same (I have just checked they have the same number of parameters and architecture for both versions)

Is your training process stable? What is the difference between different runs (for same version) and different lib versions?
