### ISSUE TITLE
PSPnet Implementation is very different than the original model

### ISSUE THREAD

**Issue by ali-masoudi** [qubvel/segmentation_models#174]
This is your PSPnet model plot:
```python
net = PSPNet(backbone_name='resnet101',
                 input_shape=(opt.image_height, opt.image_width, 3),
                 classes=20,
                 activation='softmax',
                 weights=opt.checkpoint,
                 encoder_weights='imagenet',
                 encoder_freeze=True,
                 downsample_factor=4,
                 psp_conv_filters=512,
                 psp_pooling_type='avg',
                 psp_use_batchnorm=True,
                 psp_dropout=None)
```
![PSPnet_Segmentation_Model](https://user-images.githubusercontent.com/26261766/63112337-33bc5380-bfa5-11e9-97ff-fb96ac79580f.png)
</br>
and This is the [original](https://github.com/hszhao/PSPNet/blob/master/evaluation/prototxt/pspnet101_cityscapes_713.prototxt) Caffe model which I visualized via [netscope](https://ali-masoudi.github.io/netscope/):
![original PSPNet](https://user-images.githubusercontent.com/26261766/63112257-01aaf180-bfa5-11e9-8835-aa64c63d7923.png)
</br>
As you can see the original model have much more layers.any explanation to this ?

**Comment by qubvel** [comment]
Set dowsamlple_factor to 8 or to 16. This parameter regulate the depth of encoder
