### ISSUE TITLE
May I get the trained weight in the  Multi-class segmentation on CamVid dataset?

### ISSUE THREAD

**Issue by GodZarathustra** [qubvel/segmentation_models#178]
Hi @qubvel 
I am looking for a trained model to detect objects on traffic scene（car,pedestrain,etc.）and the example code you provide is a good implementation of this scenario. But downloading the big dataset and retraining the model is hard for me, could you please open your trained model in this case:  Multi-class segmentation on CamVid dataset for me? thank you anyway!

**Comment by qubvel** [comment]
Hi @GodZarathustra 
I have train network just for 2 classes and did not save weights.
CamVid dataset is very small, you can train network by yourself using even CPU or try Google Colab service.
