### ISSUE TITLE
ValueError: Unknown loss function:binary_crossentropy + jaccard_loss

### ISSUE THREAD

**Issue by stvogel** [qubvel/segmentation_models#181]
I just tried the new 1.0.0b1-Release and trained a new model.
But when I try to load the model with keras.models.load_model(filepath) I get:
```
ValueError: Unknown loss function:binary_crossentropy + jaccard_loss
```
During training, I use bce_jaccard_loss and segmentation_models.metrics.IOUScore() as metric.
For loading I have already imported segmentation_models.
What am I doing wrong. I'm sure that's something simple.

**Comment by chAwater** [comment]
Hi @stvogel,

There is a relevant issue #172. Also a similar issue #86.

In short, the loss and metrics are `custom_objects`, you can load them by:
```python
from segmentation_models.losses  import bce_jaccard_loss
from segmentation_models.metrics import IOUScore

model = load_model(
    'model.h5', 
    custom_objects={
        'binary_crossentropy + jaccard_loss': bce_jaccard_loss,
        'iou_score': IOUScore(),
    }
)
```

---

If you load the model just for inference:
```python
model = load_model('model.h5', compile=False)
```

**Comment by qubvel** [comment]
@chAwater Thanks a lot

**Comment by stvogel** [comment]
Thanks a lot for the quick answer ... I thought I was missing something and I did a search on the issues, but without success. Thanks for helpimg me out.
