### ISSUE TITLE
I think you have a problem with the focalloss 

### ISSUE THREAD

**Issue by xiaomao19970819** [qubvel/segmentation_models#187]
In the function, you set the weights of the plus and minus samples to alpha
    loss_1 = - gt * (alpha * backend.pow((1 - pr), gamma) * backend.log(pr))
    loss_0 = - (1 - gt) * (alpha * backend.pow((pr), gamma) * backend.log(1 - pr))

**Comment by xiaomao19970819** [comment]
If anyone sees this question, I hope to get your help and answer, thank you very much

**Comment by qubvel** [comment]
Hi @xiaomao19970819 
What is the correct way from your point of view?

**Comment by xiaomao19970819** [comment]
> Hi @xiaomao19970819
> What is the correct way from your point of view?

In my opinion,alpha is used to equalize positive and negative samples
So the weights of the positive and negative  samples should not all be equal to alpha
this is my point :
loss_1 = - gt * (alpha * backend.pow((1 - pr), gamma) * backend.log(pr))
loss_0 = - (1 - gt) * ( (1-alpha) * backend.pow((pr), gamma) * backend.log(1 - pr))

**Comment by LeeJayHui** [comment]
Hi @xiaomao19970819, I agree with you. The implementation here is different from the formula of Focalloss, and it seems that your proposed modification is correct.
Hi @qubvel, maybe it's time to update the code.

**Comment by qubvel** [comment]
fixed #259
