### ISSUE TITLE
Loading PSPNet + EfficientNetB5 backbone = Unknown kwarg args

### ISSUE THREAD

**Issue by TimbusCalin** [qubvel/segmentation_models#191]
from efficientnet.model import get_swish
from efficientnet.model import get_dropout

model = load_model('model_pspnet_keras.hdf5', custom_objects={ "swish": get_swish,
                                                                                                           "FixedDropout":get_dropout})

The code from above fails because of the FixedDropout.

What is the correct way to load the FixedDropout?

Thank you in advance and congratulations for the repository, impressive.

**Comment by qubvel** [comment]
Try this
```python
import segmentation_models #important!
import keras

model = keras.models.load_model('path/to/model.h5')
```
