### ISSUE TITLE
How can I use unet model without backbones?

### ISSUE THREAD

**Issue by garipovazamat** [qubvel/segmentation_models#195]
Hello. I wanted to use U-net model, but I didn't find any way to use unet directly, without backbones. There argument 'backbone_name=None' isn't possible, by default it's equal 'vgg16'

**Comment by qubvel** [comment]
No, it is impossible, backbone is necessary part of Unet model (it play a role of encoder).

**Comment by hamzanaeem1999** [comment]
@qubvel 
Hi, I want to use GoogleNet/AlexNet as backbone of UNET, Can't we use it ?
