### ISSUE TITLE
module 'segmentation_models' has no attribute 'get_preprocessing' error

### ISSUE THREAD

**Issue by akare55** [qubvel/segmentation_models#199]
Hi everyone.
When running code, I get this error and I can't solve this error. Is there anyone know solution? I'm looking forward your replies.
![Ekran Görüntüsü - 2019-09-07 17-15-44](https://user-images.githubusercontent.com/34503743/64476069-5f40f100-d193-11e9-8d74-df725bbda9bd.png)

**Comment by qubvel** [comment]
check that you have version 1.*,
NOT 0.2.*

**Comment by akare55** [comment]
I'm sorry I'm beginner; but have can I check version?

**Comment by qubvel** [comment]
sm.__version__

**Comment by akare55** [comment]
0.2.1

**Comment by qubvel** [comment]
update to 1.0.*

**Comment by sumaira-hussain** [comment]
Hi  I am also getting same error and my version is uptodate. any solutions?

**Comment by germanjke** [comment]
helped updating to 1.0.*
but have a note: i had a restart jupyter notebook to update a version

**Comment by juburr** [comment]
`sm.__version__` reports 1.0.1.
Also restarted Jupyter notebook.
Still receiving this error.
