### ISSUE TITLE
FailedPreconditionError: Attempting to use uninitialized value

### ISSUE THREAD

**Issue by virilo** [qubvel/segmentation_models#20]
I'm trying to use a resnet-50 Unet with encoder weights from imagenet.

But I'm getting the next error:

FailedPreconditionError: Attempting to use uninitialized value decoder_stage0_bn1_5/moving_mean/biased
     [[Node: decoder_stage0_bn1_5/moving_mean/biased/read = Identity[T=DT_FLOAT, _class=["loc:@decoder_stage0_bn1_5/AssignMovingAvg"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](decoder_stage0_bn1_5/moving_mean/biased)]]

I tried both encoder_weights='imagenet' and encoder_weights=None.

```
IMAGE_SIZE=224
model = Unet(backbone_name=BACKBONE_NAME, encoder_weights='imagenet',
                 freeze_encoder=True,
                 input_shape=(IMAGE_SIZE, IMAGE_SIZE, 3))
model.compile('Adam', 'binary_crossentropy', ['binary_accuracy'])

    ...

history0 = model.fit_generator(train_gen,
                                  callbacks=[learning_rate, save_checkpoints],
                                  epochs=2,
                                  shuffle=True)

```
It seems like if the the Unet expansive path hadn't been initialized.

How could I solve this?

**Comment by virilo** [comment]
Hi,
I installed via pip segmentation_models 0.1.2
Using keras 2.2.2 and tf 0.10.1

The same error with freeze_encoder=True and with freeze_encoder=False

Thanks qubvel

**Comment by qubvel** [comment]
Did you mean tf version 1.10.1?

**Comment by qubvel** [comment]
I was **not** able to reproduce your error with following:  

**Evironment**
```
Docker image: python:3.6
tensorflow==1.10.1 (cpu)
keras==2.2.2
scikit-image==0.14.1
segmentation-model==0.1.2
```
**Code**
```python
import numpy as np
from segmentation_models import Unet

x = np.ones((160, 224, 224, 3))
y = np.ones((160, 224, 224, 1))

model = Unet('resnet50', encoder_weights='imagenet',
                 freeze_encoder=True,
                 input_shape=(224, 224, 3))

model.compile('Adam', 'binary_crossentropy', ['binary_accuracy'])
model.fit(x, y, epochs=10)
```

Everything works fine, maybe something wrong with your environment?

**Comment by virilo** [comment]
Hi Pavel,

There was a bug in a piece of my code that I didn't write in the issue summary.

I was using importing a tensorflow package (from tf.keras.callbacks) instead of importing from keras.callbacks

This solved my problem:
learning_rate = keras.callbacks.LearningRateScheduler(cosine_annealing) 

Thanks a lot for helping me and for your pretty segmentation models library!
