### ISSUE TITLE
Model Evaluation: Invalid Argument Error: Invalid Shape

### ISSUE THREAD

**Issue by codeeppy** [qubvel/segmentation_models#200]
Hello everyone,

I am trying to train the model on a dataset of shape (448*448*3). After the successful training the model evaluation is giving an error code like this:
![Untitled 1](https://user-images.githubusercontent.com/42350574/64629522-a2999a80-d3f3-11e9-8a38-b3789621d1d5.png)

And also the prediction mask is not generating as well,

![Untitled](https://user-images.githubusercontent.com/42350574/64629554-b1804d00-d3f3-11e9-8246-403ae1e78e33.png)
 Please, help me solve this issue!!

**Comment by qubvel** [comment]
Something wrong with data you pass to the model, check output from dataloader (image shapes and range).

**Comment by codeeppy** [comment]
Yes, I was feeding a different shape for the test data and without providing the (gt) masks.
Now everything works fine.
Thanks :)
