### ISSUE TITLE
module 'segmentation_models' has no attribute 'get_preprocessing' 

### ISSUE THREAD

**Issue by sumaira-hussain** [qubvel/segmentation_models#203]
Hi 
I am using segmentation module to run Unet but I am getting error on 
from segmentation-models.backbone import get_preprocessing

I have updated my segmentation module to latest version but the problem still exists.
![image](https://user-images.githubusercontent.com/23133444/64680973-6d538200-d4b1-11e9-8c18-1f3945d682bd.png)

**Comment by sumaira-hussain** [comment]
@qubvel

**Comment by qubvel** [comment]
Check version (sm.__version__)

**Comment by sumaira-hussain** [comment]
> Check version (`sm.__version__`) and read previous issues.

This isn't working in my program

**Comment by sumaira-hussain** [comment]
> Check version (`sm.__version__`) and read previous issues.

Already updated segmentation models according to previous issues

**Comment by qubvel** [comment]
What is the output of `sm.__version__`?
If it is 1.0 get_preprocessing is located in sm.get_prepocessing (see example carefully)

**Comment by ishankjain** [comment]
> It is 1.0 and the issue is resolved. Thank you

how yo have resolved the issue, please help

**Comment by SuMyatNoe29** [comment]
I have downgraded to 1.0 and it does not solve the issues. Please help me.

**Comment by jamal-ansary** [comment]
Upgrade the package using : pip3 install --user --upgrade segmentation-models
