### ISSUE TITLE
'Dataloder' object is not an iterator

### ISSUE THREAD

**Issue by sainatarajan** [qubvel/segmentation_models#206]
Can someone help why I am getting this error? I am using a PSPNet model with 2 classes for my custom dataset. Here is the stack trace:

`
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-21-9bb7e6991b88> in <module>
      1 print(len(train_dataloader))
----> 2 fitted_model= model.fit_generator(train_dataloader,  steps_per_epoch=len(train_dataloader), epochs=10, callbacks=callbacks,)

~/anaconda3/lib/python3.7/site-packages/keras/legacy/interfaces.py in wrapper(*args, **kwargs)
     89                 warnings.warn('Update your `' + object_name + '` call to the ' +
     90                               'Keras 2 API: ' + signature, stacklevel=2)
---> 91             return func(*args, **kwargs)
     92         wrapper._original_function = func
     93         return wrapper

~/anaconda3/lib/python3.7/site-packages/keras/engine/training.py in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
   1416             use_multiprocessing=use_multiprocessing,
   1417             shuffle=shuffle,
-> 1418             initial_epoch=initial_epoch)
   1419 
   1420     @interfaces.legacy_generator_methods_support

~/anaconda3/lib/python3.7/site-packages/keras/engine/training_generator.py in fit_generator(model, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
    179             batch_index = 0
    180             while steps_done < steps_per_epoch:
--> 181                 generator_output = next(output_generator)
    182 
    183                 if not hasattr(generator_output, '__len__'):

~/anaconda3/lib/python3.7/site-packages/keras/utils/data_utils.py in get(self)
    707                     "`use_multiprocessing=False, workers > 1`."
    708                     "For more information see issue #1638.")
--> 709             six.reraise(*sys.exc_info())

~/anaconda3/lib/python3.7/site-packages/six.py in reraise(tp, value, tb)
    691             if value.__traceback__ is not tb:
    692                 raise value.with_traceback(tb)
--> 693             raise value
    694         finally:
    695             value = None

~/anaconda3/lib/python3.7/site-packages/keras/utils/data_utils.py in get(self)
    683         try:
    684             while self.is_running():
--> 685                 inputs = self.queue.get(block=True).get()
    686                 self.queue.task_done()
    687                 if inputs is not None:

~/anaconda3/lib/python3.7/multiprocessing/pool.py in get(self, timeout)
    655             return self._value
    656         else:
--> 657             raise self._value
    658 
    659     def _set(self, i, obj):

~/anaconda3/lib/python3.7/multiprocessing/pool.py in worker(inqueue, outqueue, initializer, initargs, maxtasks, wrap_exception)
    119         job, i, func, args, kwds = task
    120         try:
--> 121             result = (True, func(*args, **kwds))
    122         except Exception as e:
    123             if wrap_exception and func is not _helper_reraises_exception:

~/anaconda3/lib/python3.7/site-packages/keras/utils/data_utils.py in next_sample(uid)
    624         The next value of generator `uid`.
    625     """
--> 626     return six.next(_SHARED_SEQUENCES[uid])
    627 
    628 

TypeError: 'Dataloder' object is not an iterator
`

**Comment by JordanMakesMaps** [comment]
It looks like `train_dataloader` isn't an actual python generator and/or it's not returning/yielding the batches correctly.

What's the code for it look like?

**Comment by JordanMakesMaps** [comment]
For your reference, here's what I use, note that it a child of `keras.utils.Sequence`:

`# Image data generator class
class DataGenerator(keras.utils.Sequence):
    
    def __init__(self, dataframe, batch_size, augment, n_classes = 8):
        self.dataframe = dataframe
        self.batch_size = batch_size
        self.n_classes = n_classes
        self.augment = augment
          
        
    # Steps per epoch    
    def __len__(self):
        return len(self.dataframe) // self.batch_size
    
    # Shuffles and resets the index at the end of training epoch
    def on_epoch_end(self):
        self.dataframe = self.dataframe.reset_index(drop = True)
    
    
    # Generates data, feeds to training
    def __getitem__(self, index):
        
        global preprocess_input
        
        processed_images = []
        processed_masks = []
        
        for _ in range(self.batch_size):

            the_image = io.imread(self.dataframe['Images'][index])
            the_mask = np.load(self.dataframe['Masks'][index]).astype('uint8');
            one_hot_mask = one_hot_encoder(the_mask, 8)
            
            if(self.augment):
                
                processed_image = augs_for_images(image = the_image)
                processed_mask = augs_for_masks(image = one_hot_mask)
         
            else:
                # Still resizing and then random cropping, but no augmentations   
                processed_image = resize_for_images(image = the_image)
                processed_mask = resize_for_masks(image = one_hot_mask)

            processed_images.append(preprocess_input(processed_image))
            processed_masks.append(processed_mask)

                
        batch_x = np.array( processed_images )
        batch_y = np.array( processed_masks )
        
        return (batch_x, batch_y)`

**Comment by sainatarajan** [comment]
Thank you for your reply. Here is the actual code:

`train_dataset = Dataset(
    FRAME_PATH, 
    MASK_PATH, 
    classes=['sky', 'road'],
)

val_dataset = Dataset(
    DATA_PATH+'/test/images/', 
    DATA_PATH+'/train/masks/', 
    classes=['sky', 'road'],
)

train_dataloader = Dataloder(train_dataset, batch_size=1, shuffle=True)
val_dataloader = Dataloder(val_dataset, batch_size=1, shuffle=True)

callbacks = [
    tensorflow.keras.callbacks.ModelCheckpoint('./best_model.h5', save_weights_only=True, save_best_only=True, mode='min'),
    tensorflow.keras.callbacks.ReduceLROnPlateau(),
]

n_classes= 2
dice_loss = sm.losses.DiceLoss()
focal_loss = sm.losses.BinaryFocalLoss() if n_classes == 1 else sm.losses.CategoricalFocalLoss()
total_loss = dice_loss + (1 * focal_loss)
metrics = [sm.metrics.IOUScore(threshold=0.5), sm.metrics.FScore(threshold=0.5)]
model.compile(optimizer= 'adam', loss= total_loss, metrics= metrics)

fitted_model= model.fit_generator(train_dataloader,  
        steps_per_epoch=len(train_dataloader),
        epochs=1, 
        callbacks=callbacks,
)
`
The error is generated when I run model.fit_generator()

**Comment by sainatarajan** [comment]
@JordanMakesMaps 
There error still persists in my case. When I used your code instead of Dataloder, it showed cannot convert string to index. Can you share the code of your project?

**Comment by JordanMakesMaps** [comment]
Might be an issue with how you're initiating the model or the data generator?

```python
# Image data generator class
class DataGenerator(keras.utils.Sequence):
    
    def __init__(self, dataframe, batch_size, augment, n_classes = 8):
        self.dataframe = dataframe
        self.batch_size = batch_size
        self.n_classes = n_classes
        self.augment = augment
          
        
    # Steps per epoch    
    def __len__(self):
        return len(self.dataframe) // self.batch_size
    
    # Shuffles and resets the index at the end of training epoch
    def on_epoch_end(self):
        self.dataframe = self.dataframe.reset_index(drop = True)
    
    
    # Generates data, feeds to training
    def __getitem__(self, index):
        
        global preprocess_input
        
        processed_images = []
        processed_masks = []
        
        for _ in range(self.batch_size):

            the_image = io.imread(self.dataframe['Images'][index])
            the_mask = np.load(self.dataframe['Masks'][index]).astype('uint8');
            one_hot_mask = one_hot_encoder(the_mask, 8)
            
            if(self.augment):
                
                processed_image = augs_for_images(image = the_image)
                processed_mask = augs_for_masks(image = one_hot_mask)
         
            else:
                # Still resizing, but no augmentations   
                processed_image = resize_for_images(image = the_image)
                processed_mask = resize_for_masks(image = one_hot_mask)

            processed_images.append(preprocess_input(processed_image))
            processed_masks.append(processed_mask)

                
        batch_x = np.array( processed_images )
        batch_y = np.array( processed_masks )
        
        return (batch_x, batch_y)
   
train_gen = DataGenerator(train, batch_size = batch_size, augment = True)
valid_gen = DataGenerator(valid, batch_size = batch_size, augment = False)
 
... 
# create model
# compile model
# set callbacks
...

history = model.fit_generator(generator = train_gen, 
                              steps_per_epoch = train_steps, 
                              epochs = 1, 
                              validation_data = valid_gen,
                              validation_steps = valid_steps,
                              verbose = 1,
                              callbacks = holla)
```

**Comment by sainatarajan** [comment]
@JordanMakesMaps As you said, there are some issues in the code of the data generator. I tried your code and got passed some small issues. Can you give the code of the class dataframe (passed as an argument to init in the class DataGenerator) which you have used in the DataGenerator class? I think this would solve the problem since the two classes (your DataGenerator and the repo's Dataset classes) seem incompatible.

**Comment by sainatarajan** [comment]
@JordanMakesMaps I tried to edit the repo from here and it got past the original error but threw an error saying:
`ValueError: Error when checking target: expected softmax to have shape (768, 1152, 2) but got array with shape (768, 1152, 3)`

**Comment by JordanMakesMaps** [comment]
`train` and `valid` are just pandas' dataframes with two columns: 'Images' and 'Masks' which are paths to the files themselves.

`ValueError: Error when checking target: expected softmax to have shape (768, 1152, 2) but got array with shape (768, 1152, 3)` 

That might be caused by how you provide the training mask to the model or how many classes the model expected when first initiated. In my Generator class, during the preprocessing phase I create a one-hot-encoded vector to represent the mask in the form that Keras expects. Are you using `to_categorical()`, the function provided by Keras? Either way, you might want to look at what the output shape is of the one-hot-encoded vector as it might be the source of the problem.

**Comment by sainatarajan** [comment]
@JordanMakesMaps Thank you !!! I have managed to run and get a decent output (fewer data and small epochs). As you said I solved the shape error by editing the model definition by changing the number of classes to 3. This lead to another error: 
`Error: Attempting to use uninitialized value of Adam_Lr21`. I had solved it by removing the callbacks from the `fit_generator()` method.
