### ISSUE TITLE
ValueError: 'binary_crossentropy + jaccard_loss' is not a valid scope name

### ISSUE THREAD

**Issue by KuenstlicheIntelligenz** [qubvel/segmentation_models#209]
Using 
tensorflow=1.14 and python 3.6

installed keras with conda install -c conda-forge keras
and the other pagackes i needed following:
https://github.com/Diyago/ML-DL-scripts/blob/master/DEEP%20LEARNING/segmentation/Segmentation%20pipeline/segmentation%20pipeline.ipynb

pip install git+https://github.com/qubvel/efficientnet
pip install git+https://github.com/qubvel/classification_models.git
pip install git+https://github.com/qubvel/segmentation_models

```
Traceback (most recent call last):
  File "model.py", line 256, in <module>
    loss=bce_jaccard_loss, metrics=[iou_score])
  File "/opt/conda/lib/python3.6/site-packages/keras/engine/training.py", line 229, in compile
    self.total_loss = self._prepare_total_loss(masks)
  File "/opt/conda/lib/python3.6/site-packages/keras/engine/training.py", line 692, in _prepare_total_loss
    y_true, y_pred, sample_weight=sample_weight)
  File "/opt/conda/lib/python3.6/site-packages/keras/losses.py", line 70, in __call__
    with K.name_scope(scope_name):
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 6513, in __enter__
    return self._name_scope.__enter__()
  File "/opt/conda/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 4307, in name_scope
    raise ValueError("'%s' is not a valid scope name" % name)
ValueError: 'binary_crossentropy + jaccard_loss' is not a valid scope name
```

I guess its caused because of the " + " which is not allowed to be used in a scope name. (empty spaces and +)
If i change that my code runs.
The name is constructed in:
segmentation_models/base/objects.py

**Comment by qubvel** [comment]
Thanks for report, are you using tf.keras version?

**Comment by LeonShangguan** [comment]
I have the similar issue with `'binary_focal_loss` + dice_loss' is not a valid scope name`. Not using tf.keras version, with tensorflow version: 1.14.0 and keras version: 2.3.0

**Comment by LeonShangguan** [comment]
@KuenstlicheIntelligenz @qubvel I solve the problem by changing the class `SumOfLosses(Loss)`, which is defined in `segmentation_models/base/objects.py`. Only change the initial function `name = '{} + {}'.format(l1.__name__, l2.__name__)` to `name = '{} _ {}'.format(l1.__name__, l2.__name__)`. So definitely the problem is caused by "+".

**Comment by KuenstlicheIntelligenz** [comment]
> Thanks for report, are you using tf.keras version?

Nope

**Comment by qubvel** [comment]
@LeonShangguan would you like to make a PR to fix this?

**Comment by Chinmay26** [comment]
Encountered this error and wanted to give heads up that this is happening for other characters such as (+* ) & others. May need to look at valid TF scope character set
