### ISSUE TITLE
Cannot import any loss or metrics

### ISSUE THREAD

**Issue by SarahDixon** [qubvel/segmentation_models#212]
Hi there, I've been using your models for a segmentation task (which has imported fine), but I can't import any of the loss functions or metrics. Any help would be appreciated!

Code:

**metrics = [sm.metrics.IOUScore(threshold=0.5), sm.metrics.FScore(threshold=0.5)]**
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-8-ddc22577e188> in <module>
----> 1 metrics = [sm.metrics.IOUScore(threshold=0.5), sm.metrics.FScore(threshold=0.5)]

AttributeError: module 'segmentation_models.metrics' has no attribute 'IOUScore'

**loss = [sm.losses.CategoricalCELoss(), sm.losses.JaccardLoss()]**

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-10-e2ce3d81bf11> in <module>
----> 1 loss = [sm.losses.CategoricalCELoss(), sm.losses.JaccardLoss()]

AttributeError: module 'segmentation_models.losses' has no attribute 'CategoricalCELoss'

**Comment by qubvel** [comment]
Check library version, make sure it is updated to 1.*
```python
>>> sm.__version__
```

**Comment by SarahDixon** [comment]
thank you! Works perfectly now
