### ISSUE TITLE
AttributeError: 'Model' object has no attribute 'weighted_metrics' while calling set_trainable

### ISSUE THREAD

**Issue by benqua** [qubvel/segmentation_models#215]
Hi,

while calling set_trainable(true) to fine tune a model (following the tutorial here: https://segmentation-models.readthedocs.io/en/latest/tutorial.html#fine-tuning ), I get the following error:
```
  File "experiment0.py", line 75, in run_exp
    set_trainable(model)
  File "/home/benq/anaconda3/envs/tf2/lib/python3.7/site-packages/segmentation_models/utils.py", line 36, in set_trainable
    weighted_metrics=model.weighted_metrics,
AttributeError: 'Model' object has no attribute 'weighted_metrics'
```

the model is Unet with resnet34 backbone, running on tensorflow 2.0.
The first call tomodel.fit_generator works without issue.

Any idea?

**Comment by qubvel** [comment]
May be something changed in API,
You can just copy paste code of this function and remove `weighted_metrics=model.weighted_metrics` this line

**Comment by benqua** [comment]
Ok, thank you for your answer, I will try that.

Do you have any plan to officially support tensorflow 2.0 ?

**Comment by qubvel** [comment]
As far as I understand tf2 support tf.keras API
Thi is models just build using this API, so everything should be compatible

**Comment by marcomameli1992** [comment]
I try your code and before yesterday it works, but yesterday when I try to recompile the network I obtain the error reported here, more precisely I have: 

> Traceback (most recent call last):
>   File "training.py", line 83, in <module>
>     sm.utils.set_trainable(model=model, recompile=True)
>   File "/usr/local/lib/python3.6/dist-packages/segmentation_models/utils.py", line 36, in set_trainable
>     weighted_metrics=model.weighted_metrics,
> AttributeError: 'Model' object has no attribute 'weighted_metrics'

The same error of benqua, but I use Tensorflow-gpu 1.13.2 and I try tensorflow-gpu 1.15.0 and after the deletion of the 

> weighted_metrics=model.weighted_metrics

the result is an error on fit_generator:

> Epoch 1/80
> Traceback (most recent call last):
>   File "training.py", line 120, in <module>
>     validation_steps=len(valid_dataloader)
>   File "/usr/local/lib/python3.6/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 1732, in fit_generator
>     initial_epoch=initial_epoch)
>   File "/usr/local/lib/python3.6/dist-packages/keras/engine/training_generator.py", line 220, in fit_generator
>     reset_metrics=False)
>   File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 1514, in train_on_batch
>     outputs = self.train_function(ins)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/backend.py", line 3076, in call
>     run_metadata=self.run_metadata)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1439, in call
>     run_metadata_ptr)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/errors_impl.py", line 528, in exit
>     c_api.TF_GetCode(self.status.status))
> tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'softmax_target' with dtype float and shape [?,?,?,?]
>          [[{{node softmax_target}}]]
>          [[{{node Mean_1}}]]

I don't know how to solve this issue. Can you help me, please?

**Comment by systemallica** [comment]
I'm facing the same error, is there a known fix? @qubvel

**Comment by victor-roris** [comment]
I have the same error. 

I made a workaround where I assign the original loss and metric functions instead of reusing the stored in the model. 

```
## Fine tunning
model = Unet(BACKBONE,  classes=n_class, encoder_weights='imagenet', activation = "softmax", encoder_freeze=True)

# First compile (with loss and metrics)
loss = sm.losses.categorical_focal_dice_loss
metrics = [sm.metrics.IOUScore(threshold=0.5), sm.metrics.FScore(threshold=0.5)]
model.compile(keras.optimizers.Adam(LR), loss=loss, metrics=metrics)

# pretrain model decoder
model.fit_generator( generator = train_dataloader, steps_per_epoch=len(train_dataloader), epochs=2)

# copy-paste code of the set_trainable function with modifications
for layer in model.layers:
    layer.trainable = True
model.compile(
    model.optimizer,
    loss=loss,            #I re-assing the original loss function
    metrics=metrics,  #I re-assing the original metric function
#   loss=model.loss,
#   metrics=model.metrics,
    loss_weights=model.loss_weights,
    sample_weight_mode=model.sample_weight_mode,
#    weighted_metrics=model.weighted_metrics,
        )

# train model
history = model.fit_generator(
    generator = train_dataloader, 
    steps_per_epoch=len(train_dataloader), 
    epochs=100, 
    validation_data=valid_dataloader, 
    validation_steps=len(valid_dataloader),
)
```

It works but I don't know if It is technically correct.
