### ISSUE TITLE
Segmentation models import error

### ISSUE THREAD

**Issue by Alpich** [qubvel/segmentation_models#216]
Hi, i am trying to import segmentation models like this:
"import segmentation_models as sm", but getting an error

![image](https://user-images.githubusercontent.com/56114562/66127350-16465600-e5f4-11e9-9a02-fc1cc2d8a0b5.png)

**Comment by qubvel** [comment]
Hi please provide all packages versions (for all dependencies and package itself)

**Comment by Alpich** [comment]
Hi again, versions here
Python 3.6.5
Keras 2.3
Keras app 1.0.8
Efficientnet 1.0
Segmentation models 0.2.1
tensorflow 1.11 
Also my CPU doesnt support AVX technology (only SSE, and thats why i use tensorflow 1.11 instead 1.13) can it be critical?
And what exact python version are you use?

**Comment by sainatarajan** [comment]
Update your packages to the latest versions. Tensorflow has 1.14.0 and Keras has 2.2.4 as the latest versions.

**Comment by Alpich** [comment]
Update helped, ty @sainatarajan
