### ISSUE TITLE
Is there any way I can embed this package into an exe?

### ISSUE THREAD

**Issue by kjodha** [qubvel/segmentation_models#217]
Hi @qubvel !!
I was using this package and was trying to create an executable using auto-py-to-exe, but I think there is some issue with the FrozenImporter class. Is it possible or is there any other way around this problem that I can create a OneFile executable of a python code where I'm using this package.

**Comment by qubvel** [comment]
Hi, I have no idea, never heard about it. Leave this issue open, maybe someone will help you.

**Comment by kjodha** [comment]
@qubvel : I figured it out. It was an issue with the new version of Pyinstaller which was being used by auto-py-to-exe tool while creating and executable. The new version does not supports the OneFile executable conversion of a python code, but does works for OneDirectory conversion. For now, I'm using OneDirectory format to embed this package in a directory to be used by the converted executable. Thank you though for your response. I'm closing the issue.
