### ISSUE TITLE
fix requirements again 

### ISSUE THREAD

**Issue by srcolinas** [qubvel/segmentation_models#218]
Hi! your `requirements.txt` does not have all necessary dependencies to run your tests (e.g. scikit-image), is this intended? I saw the closed issue #47 and the fix included scikit-image, which is now gone.

**Comment by qubvel** [comment]
Hi
install package in dev mode to run tests (it will install pytest and scikit-image)  
`pip install segmentation-models[tests]`

**Comment by srcolinas** [comment]
thanks!
