### ISSUE TITLE
efficientnet Backbone not working

### ISSUE THREAD

**Issue by tonychenxyz** [qubvel/segmentation_models#219]
Here is the error when I use any of the efficientnets as backbone (with Unet).

`TypeError                                 Traceback (most recent call last)
<ipython-input-22-a9a36cd6d5fb> in <module>
      2     'efficientnetb2',
      3     classes=4,
----> 4     input_shape=(320, 480, 3)
      5 )
      6 model.compile(optimizer=Nadam(lr=0.0002), loss=bce_dice_loss, metrics=[dice_coef])

~/anaconda3/envs/deep_learning/lib/python3.7/site-packages/segmentation_models/utils.py in wrapper(*args, **kwargs)
     29                     kwargs[new_arg] = kwargs[old_arg]
     30 
---> 31             return func(*args, **kwargs)
     32 
     33         return wrapper

~/anaconda3/envs/deep_learning/lib/python3.7/site-packages/segmentation_models/unet/model.py in Unet(backbone_name, input_shape, classes, activation, encoder_weights, encoder_freeze, encoder_features, decoder_block_type, decoder_filters, decoder_use_batchnorm, **kwargs)
     61                             input_tensor=None,
     62                             weights=encoder_weights,
---> 63                             include_top=False)
     64 
     65     if encoder_features == 'default':

~/anaconda3/envs/deep_learning/lib/python3.7/site-packages/segmentation_models/backbones/__init__.py in get_backbone(name, *args, **kwargs)
     73 
     74 def get_backbone(name, *args, **kwargs):
---> 75     return Classifiers.get_classifier(name)(*args, **kwargs)
     76 
     77 

~/anaconda3/envs/deep_learning/lib/python3.7/site-packages/classification_models/__init__.py in get_classifier(cls, name)
     84     @classmethod
     85     def get_classifier(cls, name):
---> 86         return cls._models.get(name)[0]
     87 
     88     @classmethod

TypeError: 'NoneType' object is not subscriptable`

**Comment by qubvel** [comment]
Install efficientnet, please:
`pip install efficientnet`

**Comment by tonychenxyz** [comment]
> Install efficientnet, please:
> `pip install efficientnet`

Thank you! I tried, but it didn't work. I also tried the solutions in #198 

efficientnet of 1.0.0 and segmentation-tools of 1.0.0b1 yields this when importing segmentation-models

`Segmentation Models: using `keras` framework.
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-7b517fb8177d> in <module>
     19 from tqdm import tqdm
     20 from sklearn.model_selection import train_test_split
---> 21 import segmentation_models as sm

~/anaconda3/envs/deep_learning/lib/python3.7/site-packages/segmentation_models/__init__.py in <module>
    109 
    110 # wrap segmentation models with framework modules
--> 111 from .backbones.backbones_factory import Backbones
    112 from .models.unet import Unet as _Unet
    113 from .models.pspnet import PSPNet as _PSPNet

~/anaconda3/envs/deep_learning/lib/python3.7/site-packages/segmentation_models/backbones/backbones_factory.py in <module>
      1 import copy
      2 import efficientnet.model as eff
----> 3 from classification_models.models_factory import ModelsFactory
      4 
      5 from . import inception_resnet_v2 as irv2

ModuleNotFoundError: No module named 'classification_models.models_factory'`

Using efficientnet of 0.0.4 and segmentation-tools of 0.2.1  yields this when print(efficientnet.__version__)

`AttributeError                            Traceback (most recent call last)
<ipython-input-4-20f8b48cd739> in <module>
      2 import efficientnet
      3 print(sm.__version__)
----> 4 print(efficientnet.__version__)

AttributeError: module 'efficientnet' has no attribute '__version__'`

When loading backbone, still

`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-10-23828e96fe70> in <module>
      2     'efficientnetb0',
      3     classes=4,
----> 4     input_shape=(320, 480, 3)
      5 )
      6 model.compile(optimizer=Nadam(lr=0.0002), loss=bce_dice_loss, metrics=[dice_coef])

~/anaconda3/envs/deep_learning/lib/python3.7/site-packages/segmentation_models/utils.py in wrapper(*args, **kwargs)
     29                     kwargs[new_arg] = kwargs[old_arg]
     30 
---> 31             return func(*args, **kwargs)
     32 
     33         return wrapper

~/anaconda3/envs/deep_learning/lib/python3.7/site-packages/segmentation_models/unet/model.py in Unet(backbone_name, input_shape, classes, activation, encoder_weights, encoder_freeze, encoder_features, decoder_block_type, decoder_filters, decoder_use_batchnorm, **kwargs)
     61                             input_tensor=None,
     62                             weights=encoder_weights,
---> 63                             include_top=False)
     64 
     65     if encoder_features == 'default':

~/anaconda3/envs/deep_learning/lib/python3.7/site-packages/segmentation_models/backbones/__init__.py in get_backbone(name, *args, **kwargs)
     73 
     74 def get_backbone(name, *args, **kwargs):
---> 75     return Classifiers.get_classifier(name)(*args, **kwargs)
     76 
     77 

~/anaconda3/envs/deep_learning/lib/python3.7/site-packages/classification_models/__init__.py in get_classifier(cls, name)
     84     @classmethod
     85     def get_classifier(cls, name):
---> 86         return cls._models.get(name)[0]
     87 
     88     @classmethod

TypeError: 'NoneType' object is not subscriptable
`

**Comment by tonychenxyz** [comment]
> Install efficientnet, please:
> `pip install efficientnet`

Worked by pip install git+https://github.com/qubvel/efficientnet
pip install git+https://github.com/qubvel/classification_models.git
pip install git+https://github.com/qubvel/segmentation_models
Thanks.

**Comment by qubvel** [comment]
try install it again with source code
`pip install -U git+https://github.com/qubvel/segmentation_models`
