### ISSUE TITLE
losses are functions, not classes?

### ISSUE THREAD

**Issue by gkaissis** [qubvel/segmentation_models#222]
Is it intentional behavior that loss functions are functions instead of classes or am I missing something? Should they be passed as partial functions to the model.compile function?

**Comment by qubvel** [comment]
Losses are classes, look at https://github.com/qubvel/segmentation_models/blob/master/segmentation_models/losses.py

**Comment by qubvel** [comment]
Check that you have latest version (1.*)

**Comment by gkaissis** [comment]
Thanks! Great library, by the way! 👍🏼
