### ISSUE TITLE
Memory consumption issue/question

### ISSUE THREAD

**Issue by nicemanis** [qubvel/segmentation_models#224]
Not sure if this is an issue but I have a question about memory consumption.
I am currently working with a lot of 512x512 images; therefore, I implemented a generator with flow_from_directory. However, this did not really resolve my memory consumption issues.

I checked with `nvidia-smi` what is the memory consumption of the process and it always showed the same amount of memory consumed regardless of what decoder or backbone I was using. To be specific, it consumed `7326MiB / 7618MiB`.

Is this normal behavior or is there some kind of buffer that reserves the same memory amount every time? Can you suggest anything to bring down memory consumption?

*EDIT:*
All memory is consumed after executing the following command:
```
model = sm.Unet(
    BACKBONE,
    encoder_weights=ENCODER_WEIGHTS,
    input_shape=(512, 512, 3),
    classes=1
)
```

**Comment by qubvel** [comment]
Hi, 
1) tensorflow allocate all available gpu memory
2) data generator prevent problems with RAM consumption, not GPU memory

Reduce batch size to be able to train model, or take smaller backbone.

**Comment by nicemanis** [comment]
Ok, thanks for the help
