### ISSUE TITLE
Loading res-net weights without Internet

### ISSUE THREAD

**Issue by PN12** [qubvel/segmentation_models#234]
Hi,

I am trying to run the below command on kaggle inference kernel without Internet : 

base_model = Unet(backbone_name='resnet50', 
encoder_weights='../input/resnet50/resnet50_weights_tf_dim_ordering_tf_kernels_notop.h5' , 
                  activation = 'softmax' , 
                  classes = 4)

And I am facing the below error :
**ValueError: You are trying to load a weight file containing 107 layers into a model with 104 layers.**

Could you please direct me where I am heading wrong?

Thanks

**Comment by qubvel** [comment]
You are loading not compatible weights. Look at the link for loading weights with internet and load correct weights.

**Comment by PN12** [comment]
Okay Thanks,
Can you suggest how can image input size which is not a multiple of 32 be amended in Unet Models?

**Comment by qubvel** [comment]
Use padding or resize image to nearest shape which will be divisible by 32

**Comment by PN12** [comment]
Cool , Thanks.
