### ISSUE TITLE
Dowloading model weights issue (Linknet)

### ISSUE THREAD

**Issue by Alpich** [qubvel/segmentation_models#237]
Hi, 
I started working with Linknet with this simple code.
```
import keras
import segmentation_models as sm
from segmentation_models import Linknet
model = Linknet()
```
I start it and got this message
![image](https://user-images.githubusercontent.com/56114562/67856564-e1abb880-fb25-11e9-873b-1f1cb1f378b8.png)
As I understand it, it starts to load weights from the link
[https://github.com/fchollet/deep-learning-models/releases/download/v0.1/vgg16_weights_tf_dim_ordering_tf_kernels_notop.h5](url)
But after a some time its stops with this error:
ConnectionResetError: [WinError 10054] The remote host forcibly terminated the existing connection
![image](https://user-images.githubusercontent.com/56114562/67856786-639be180-fb26-11e9-8405-910928bfd799.png)
Next I decided to download weight manually from the link and indicate path to them in the code just like this 
```
import keras
import segmentation_models as sm
from segmentation_models import Linknet
model = Linknet(weight = 'C://vgg16_weights_tf_dim_ordering_tf_kernels_notop.h5')

```
Message at the start little change, but there is no result
![image](https://user-images.githubusercontent.com/56114562/67857311-7f53b780-fb27-11e9-86ec-374bce36a6ea.png)

I also try this on another computer and another neural network, but the result is the same.

**Comment by qubvel** [comment]
Hi, to load pretrained weights you should specify `encoder_weights`
```model = Linknet(encoder_weights = 'C://vgg16_weights_tf_dim_ordering_tf_kernels_notop.h5')```

**Comment by Alpich** [comment]
Ty @qubvel. I also update models from 0.2 to 1.0 and now its work
