### ISSUE TITLE
Export to saved_model.pb for TF serving

### ISSUE THREAD

**Issue by swarmt** [qubvel/segmentation_models#238]
Thanks for the excellent library!

Hoping someone could provide a method to export as a saved_model.pb for use with tensorflow serving?

I assume one would need to include the model specific preprocessing function.

**Comment by qubvel** [comment]
You can add a few Lambda layers on top of the model with preprocessing:
```python
# pseudocode

# add preprocessing
base_model = Unet()
inp = keras.layers.Input()
x = keras.layers.Lambda(lambda x: x / 127.5 - 0.5)(inp)
x = base_model(x)
model = keras.models.Model(inp, x)

# export code here
...
```
