### ISSUE TITLE
PSPNet  upsampling layer 

### ISSUE THREAD

**Issue by OzzyTao** [qubvel/segmentation_models#241]
when I was running PSPNet, I found its result is quite coarse. When comparing with other implementations, this package uses nearest interpolation for the final upsampling layer while other packages use bilinear. I'm wondering if this could be the reason. I didn't find any information from the original paper.  My goal is to get smoother boundaries.

**Comment by JordanMakesMaps** [comment]
I noticed the same thing. I switched to UNet with the efficientnet-b3 backbone and have gotten more smooth results.

**Comment by Fuyaoyao** [comment]
I met the same tissue 6 months ago, hoping author to slove it.

**Comment by OzzyTao** [comment]
I'm testing bilinear interpolation, the result looks certainly in a finer granularity, however, I think PSPnet seems harder to train and takes many more epoches to converge than e.g., UNet. Still, so far PSPnet performs not even close to UNet which is not what I expected. I'll try to train it with larger training data.

**Comment by TimbusCalin** [comment]
If you observe a problem in the segmentation models, please open a PR so that @qubvel  or others can have a look in their spare time.

**Comment by TimbusCalin** [comment]
We should all try to contribute as much as possible to this Repo, as Pavel did everybody a great favour by providing us NNs with good backgrounds.

I also encountered the issue that you mentioned. Please open a PR with the modified BilinearInterpolation instead of NearestNeighbour.

**Comment by JordanMakesMaps** [comment]
#90 looks related. Also, @TimbusCalin, where did you find PSP using NearestNeighbour by default? It looks like the interpolation method for upsampling is Bilinear by default?
