### ISSUE TITLE
Number of channels value is always equals 3

### ISSUE THREAD

**Issue by Daemon2017** [qubvel/segmentation_models#243]
Hello!

I'm trying to initialize model like:
`    model = Unet(input_shape=(25, 25, 1),
                 classes=90,
                 activation='softmax')`

But I'm getting an error:

> Traceback (most recent call last):
>   File "C:/Users/Daemon/PycharmProjects/atDNARelationshipDetector/train.py", line 90, in <module>
>     model = build()
>   File "C:\Users\Daemon\PycharmProjects\atDNARelationshipDetector\mymodel.py", line 119, in build
>     activation='softmax')
>   File "C:\Users\Daemon\AppData\Local\Programs\Python\Python35\lib\site-packages\segmentation_models\__init__.py", line 34, in wrapper
>     return func(*args, **kwargs)
>   File "C:\Users\Daemon\AppData\Local\Programs\Python\Python35\lib\site-packages\segmentation_models\models\unet.py", line 226, in Unet
>     **kwargs,
>   File "C:\Users\Daemon\AppData\Local\Programs\Python\Python35\lib\site-packages\segmentation_models\backbones\backbones_factory.py", line 103, in get_backbone
>     model = model_fn(*args, **kwargs)
>   File "C:\Users\Daemon\AppData\Local\Programs\Python\Python35\lib\site-packages\classification_models\models_factory.py", line 78, in wrapper
>     return func(*args, **new_kwargs)
>   File "C:\Users\Daemon\AppData\Local\Programs\Python\Python35\lib\site-packages\keras_applications\vgg16.py", line 99, in VGG16
>     weights=weights)
>   File "C:\Users\Daemon\AppData\Local\Programs\Python\Python35\lib\site-packages\keras_applications\imagenet_utils.py", line 316, in _obtain_input_shape
>     '`input_shape=' + str(input_shape) + '`')
> ValueError: The input must have 3 channels; got `input_shape=(25, 25, 1)`
> 
> Process finished with exit code 1

It looks like number of channels value does nothing.

**Comment by qubvel** [comment]
Hi, could you please, read more carefully readme and previous issues before starting a new one :) 
1) input_shape H and W should be divisible by 32.
2) if you set input_shape not equal 3, provide encoder_weights = None

**Comment by Daemon2017** [comment]
Thank you for answer! 

I've misunderstood this row in docs:
> just pass (None, None, C) to make your model be able to process images af any size, but H and W of input images should be divisible by factor 32.
and I thought, that it means "only if H and W are None, than input images must be divisible by factor 32, otherwise input images may be any size" :)
