### ISSUE TITLE
input size error

### ISSUE THREAD

**Issue by chepet** [qubvel/segmentation_models#244]
Hi! I tried to run next code:
`import segmentation_models as sm
model = sm.Unet('resnet34', input_shape = (300, 300, 3), encoder_weights = 'imagenet')`

and got an error:
**A `Concatenate` layer requires inputs with matching shapes except for the concat axis. Got inputs shapes: [(None, 20, 20, 512), (None, 19, 19, 256)]**

**Comment by qubvel** [comment]
Look at #243

**Comment by qubvel** [comment]
Shape H and W should be divisible by 32.
