### ISSUE TITLE
IoU Metric - Best Practice

### ISSUE THREAD

**Issue by ceekaay** [qubvel/segmentation_models#247]
There are several parameters like threshold, per_image, smooth-value. What is best practice to evaluate my model with a small batch size like 5?

Example:
In my batch (5,256,256,1) [B,W,H,C] there is only one image with a class present (Value=1). The other images are only background (Value=0). 

Model Prediction: Everything as background (Value=0)
- Per_Image=False: **IoU Metric = 0**   (But only one image was false predicted.)
- Per_Image=True: **IoU Metric = 0.8** 

Model Prediction: Only half of the image with a class was predicted rightfully
- Per_Image=False: **0.25**
- Per_Image=True: **0.85**

First a trained my entire dataset with per_image=False and Smooth=1e-5 and I get something about 0.5 IoU-Score. Now i thought with per_image=True and Smooth=1e-5 I should get higher values, because I additionally respect images with no classes present. But my values are only about 0.4.

In my dataset there are only small areas with classes and most of the image is background. What should I use to validate my model?

**Comment by qubvel** [comment]
1) It is better to use a threshold in metric
2) Per image or not depends on task, I usually use per_image=True
