### ISSUE TITLE
What are the default encoder_weights?

### ISSUE THREAD

**Issue by kjodha** [qubvel/segmentation_models#249]
@qubvel Do the models load 'imagenet' weights by default, even if you do not mention either of the two: encoder_weights='imagenet' or encoder_weights=None while defining the model?
If the model definition looks like this?
model = sm.Unet(BACKBONE, classes=n_classes, activation=activation) //nothing is specified in the model definition about encoder_weights

**Comment by qubvel** [comment]
If you set `encoder_weights=None` weights will not be loaded.

**Comment by kjodha** [comment]
Are these imagenet weights available under MIT license?

**Comment by qubvel** [comment]
Hmmm.. not sure, but most of the weights taken from Keras-Applications and this project is under MIT licence https://github.com/keras-team/keras-applications/blob/master/LICENSE

**Comment by qubvel** [comment]
But not sure that weights have same Licence as code

**Comment by kjodha** [comment]
@qubvel Thank you for your reply. I'm specifically using renet101 as a backbone for Unet but it'd have been great if the documentation for your library could also reflect the licenses for the imported imagenet weights for their respective backbones. The https://keras.io/applications/ explicitly states which model weights are distributed under what license and that make it easy for us to know that they are available for use or not.
