### ISSUE TITLE
use dropout in u_net

### ISSUE THREAD

**Issue by sfarahaninia73** [qubvel/segmentation_models#253]
i want use dropout for my model:
base_model  = Unet(
             'resnet34',
             encoder_weights='imagenet',
             activation='sigmoid',
             encoder_freeze = True,
             classes=1,
)
what is syntax?

**Comment by qubvel** [comment]
Hi, Unet does not have dropout argument. 
To get list of available args read the docs, please.

You can remove model last layer and add dropout by yourself, if it is really necessary.

**Comment by sfarahaninia73** [comment]
> Hi, Unet does not have dropout argument.
> To get list of available args read the docs, please.
> 
> You can remove model last layer and add dropout by yourself, if it is really necessary.

muy dataset has 133 image for train and 33 image for test.
i think This is a few amount of data for train becase resualt is not good 
i think drop out can help me.
what is your idea?
