### ISSUE TITLE
Sigmoid for multi-class classification?

### ISSUE THREAD

**Issue by JordanMakesMaps** [qubvel/segmentation_models#254]
@qubvel I saw on the readme you mentioned using a sigmoid activation function for a multi-class classification problem:

```python 
# multiclass segmentation with independent overlapping/non-overlapping class masks
model = sm.Unet('resnet34', classes=3, activation='sigmoid')
```

What's the intuition for this and do you have any resources you can point me to? I've never thought to do this but for some reason with my dataset it actually does slightly better? 

thanks

**Comment by qubvel** [comment]
Hi, look at kaggle clouds understanding challenge. Clouds masks overlap.
Another example if you would like to make segmentation for a 
whole object and its parts with a single network, e.g. mask of a man and mask of man's t-shirt.

**Comment by JordanMakesMaps** [comment]
Ah, sorry, this is an instance for multi-label scenarios? That makes sense as to why this works slightly better with my dataset. Thanks!

**Comment by junxnone** [comment]
Thanks for share the awesome project.

I have a confusion question:
If we do multi-label segmentation , the  `classes` is also should be `your classes + background` ?
or only `your classes`?

```
# multiclass segmentation with non overlapping class masks (your classes + background)
model = sm.Unet('resnet34', classes=3, activation='softmax')

# multiclass segmentation with independent overlapping/non-overlapping class masks
model = sm.Unet('resnet34', classes=3, activation='sigmoid')
```

**Comment by JordanMakesMaps** [comment]
So multi-label, although sometime used as a synonom for multi-class is actually different. Multi-label is supposed to refer to a pixel (in this context), that can have more than one label. An example for multi-image classification is an image being classified based on the clothing type, and the gender of the person wearing the clothing type (e.g. Red shirt and Man, Blue pants and Woman).

Multi-class classification is just having more than two classes (background, class 1, class 2).

```python 
# multiclass segmentation with non overlapping class masks (your classes + background)
model = sm.Unet('resnet34', classes=3, activation='softmax')
```
This refers to normal multi-class classification. I believe qubvel added the comment to inform users that yes, you *do* need to include the background class.

```python
# multiclass segmentation with independent overlapping/non-overlapping class masks
model = sm.Unet('resnet34', classes=3, activation='sigmoid')
```
Whereas this is showing that if you are doing a multi-label classification, then use a `sigmoid` activation function as opposed to a `softmax`, which, is counter-intuitive because you have multiple classes but because this is a multi-label problem this is your option.

If you're just doing a multi-class classification you need to include the background as a class.

**Comment by junxnone** [comment]
thanks，it's very clear

**Comment by HariKrishnan06082k** [comment]
> Thanks for share the awesome project.
> 
> I have a confusion question: If we do multi-label segmentation , the `classes` is also should be `your classes + background` ? or only `your classes`?
> 
> ```
> # multiclass segmentation with non overlapping class masks (your classes + background)
> model = sm.Unet('resnet34', classes=3, activation='softmax')
> 
> # multiclass segmentation with independent overlapping/non-overlapping class masks
> model = sm.Unet('resnet34', classes=3, activation='sigmoid')
> ```

I think its including background
