### ISSUE TITLE
F1-Score value differs from (2 * precision * recall) / (precision + recall)

### ISSUE THREAD

**Issue by TimbusCalin** [qubvel/segmentation_models#257]
Hello,
First of all, thank you for this awesome repository.
Second of all, I have added today recall and precision as additional metrics (from segmentation_models.metrics), to see how the training progresses.

To my surprise, the **f1-score value is much less as it should normally be.**

For example, a log from fit_generator is the following:

**precision: 0.5759 - recall: 0.7752 - iou_score: 0.5431 - f1-score: 0.5688 - f2-score: 0.5753.**

In such a case, F1-Score is (judging from the above example and F1-Score formula) **is around 0.665, not 0.568.**

What is the reason for this discrepancy?

My assumption is that the  iou+f1+f2 scores output a mean of the results (mean(precision of class 1, precision of class 2, etc), while precision = TP / TP + FP and recall = TP/TP+FN take into account only the one class in the case of binary_classification.

**Comment by SabaDD** [comment]
Hi,
How did you solve this problem? I faced the same issue for binary segmentation.
I used a threshold of 0.5 for all the metrics.
f1-score calculated by .metrics is around 10% less than a number calculated manually based on precision and recall.

**Comment by elliestath** [comment]
Hey @SabaDD 

It's an old thread but I came across the same problem now.
Did you ever understand why? Thanks!

**Comment by SabaDD** [comment]
Hey @elliestath 
Based on my memory, the difference arose from the method used to calculate the scores, 'micro' versus 'macro'.

**Comment by elliestath** [comment]
Hey @SabaDD 
It sounds reasonable, thank you so much for the answer
