### ISSUE TITLE
Retraining the model

### ISSUE THREAD

**Issue by chm60** [qubvel/segmentation_models#26]
When I attempt to train the model, it throws up the error below:

ValueError: Error when checking target: expected sigmoid to have 4 dimensions, but got array with shape (10628, 1)

What format do the labels need to be in, currently I have a list of integers ranging from 0 - 9 which represent a specific class. Am I right to think that instead the labels need to be images with bounding boxes that show where the item is in the image.

**Comment by qubvel** [comment]
You have to pass for each image (e.g. shape is HxWx3) corresponding mask with shape HxWxN, where N is a number of classes you have (+ background for multiclass problems). Read more about semantic segmentation problem.

**Comment by chm60** [comment]
Thanks :) - That saved me a lot of time. Another question if I may, do you have any resources that already contain labelled training images in that specific format, i'm struggling to find a reliable and accurate dataset.

**Comment by chm60** [comment]
Thank you again :D

**Comment by qubvel** [comment]
You`re welcome)
