### ISSUE TITLE
Working with my own data

### ISSUE THREAD

**Issue by Alpich** [qubvel/segmentation_models#265]
Hi,
I have my own dataset with images and masks. Every mask also have an annotation that contains the value of a defined class in .xml format. This method is different from the CamVid dataset. So, what is the best way to extract classes from mask?

**Comment by qubvel** [comment]
Hi,
What kind of data you have in .xml files?

**Comment by Alpich** [comment]
Here example
![image](https://user-images.githubusercontent.com/56114562/69637525-d9ce2e00-1069-11ea-88d0-d3667bb72f13.png)
And i want to extract name from red line. (This is one of my image classes.)

**Comment by qubvel** [comment]
Just parse xml file, should be a python parser for `xml -> dict` conversion
