### ISSUE TITLE
Not able to use Tf.Keras

### ISSUE THREAD

**Issue by JeremyAlain** [qubvel/segmentation_models#268]
Hi there :) 
First of all thanks a lot for this repository its amazing. 
I have an issue with using tensorflow as a backend. I follow your instructions on the readme and even tried out both options, 
i.e. 
```
SM_FRAMEWORK="tf.keras"
import segmentation_models as sm
sm.set_framework("tf.keras")
```

Unfortunately no matter what I do, as soon as I have Keras installed your module will use Keras as backend and I can switch to tf.Keras (i.e. it will always say Segmentation Models: using `keras` framework.). (Note i am using tensorflow 2.0). 

If i remove Keras from my installations, it will then use tensorflow 2.0. But somehow this should work by setting it. Can you reproduce this or do you have any idea why this is happening?

**Comment by qubvel** [comment]
Hi @JeremyAlain 
The second option is (before importing segmentation_models):
```python
import os
os.environ["SM_FRAMEWORK"] = "tf.keras"
```
not  `SM_FRAMEWORK="tf.keras"`

**Comment by qubvel** [comment]
or you can run your script with 
```bash
$ SM_FRAMEWORK=tf.keras python your_script.py
```

**Comment by JeremyAlain** [comment]
Wow i feel kinda stupid :P Thanks so much that did the trick! Did not think hard enough!!

**Comment by dimimal** [comment]
For me if i run sm.set_framework(tf.keras) throws set_framework does not exist

**Comment by qubvel** [comment]
Should be a string

**Comment by dimimal** [comment]
@qubvel  I used a string, i forgot to put "". This doesnt reflect the error of why the set_framework method is missing. Also, 
When I do this:

```
import os
os.environ["SM_FRAMEWORK"] = "tf.keras"
import segmentation_models as sm
```
I get the following error:

```
----> 1 from keras.layers import Conv2D
      2 from keras.layers import Activation
      3 from keras.models import Model
      4 
      5 from .blocks import Transpose2D_block

ModuleNotFoundError: No module named 'keras'
```
Obviously its looking for the keras module.... Any ideas?

**Comment by qubvel** [comment]
What is the version of tf and sm. Which line and file cause an error?

**Comment by dimimal** [comment]
> What is the version of tf and sm. Which line and file cause an error?

That is! I had the version 0.2.1! That's why! Thanks anyway!
