### ISSUE TITLE
Will some models of 3D be provided?

### ISSUE THREAD

**Issue by huawenqing** [qubvel/segmentation_models#27]

**Comment by huawenqing** [comment]
> at the moment, this is not in the plans

I'm look forward for that, hah. And I'm a little confused about the backbones for that's trained on classification task. Will it work on the segmentation? And I don't see the dice coefficient.
Forgive my so many questions.

**Comment by huawenqing** [comment]
> at the moment, this is not in the plans

And I encounter a preblem. My dataset is medical images with only one channel. So the input shape is (None, None, 1) which is different with the given models (None, None, 3), What can I do to deal with this?

**Comment by bluesky314** [comment]
You can copy the one channel to the rest of the channels to be identical or you can add one layer with only one filter before the pretrained model to go from 3 to 1 channels

**Comment by huawenqing** [comment]
> You can copy the one channel to the rest of the channels to be identical or you can add one layer with only one filter before the pretrained model to go from 3 to 1 channels
I don't know how to achieve the second method, could you please give me some tips?

**Comment by huawenqing** [comment]
> You can copy the one channel to the rest of the channels to be identical or you can add one layer with only one filter before the pretrained model to go from 3 to 1 channels

I don't know how to achieve the second method, could you please give me some tips?

**Comment by qubvel** [comment]
Hi, @huawenqing this is an example

```python
from segmentation_models import Unet
from keras.models import Model
from keras.layers import Input, Conv2D

# define standard model with pretrained encoder and input shape None, None 3
base_model = Unet('resnet34')

# add new input with shape None, None, 1
inp = Input(shape=(None, None, 1))
x = Conv2D(3, (1, 1))(inp) # change channels shape 1 -> 3
x = base_model(x)
model = Model(inp, x)
```

**Comment by huawenqing** [comment]
> Hi, @huawenqing this is an example
> 
> ```python
> from segmentation_models import Unet
> from keras.models import Model
> from keras.layers import Input, Conv2D
> 
> # define standard model with pretrained encoder and input shape None, None 3
> base_model = Unet('resnet34')
> 
> # add new input with shape None, None, 1
> inp = Input(shape=(None, None, 1))
> x = Conv2D(3, (1, 1))(inp) # change channels shape 1 -> 3
> x = base_model(x)
> model = Model(inp, x)
> ```

Thank you very much！
