### ISSUE TITLE
DiceLoss define

### ISSUE THREAD

**Issue by yasohasakii** [qubvel/segmentation_models#278]
Hi @qubvel I noticed the `DiceLoss` define in your tutorial [segmentation_models.losses.DiceLoss](https://segmentation-models.readthedocs.io/en/latest/api.html#segmentation_models.losses.DiceLoss) is very similar to your `F-Score` define [F-Score](https://segmentation-models.readthedocs.io/en/latest/api.html#segmentation_models.metrics.FScore). I searched `Sørensen–Dice coefficient` on Wikipedia is same as you described in [ source code](https://github.com/qubvel/segmentation_models/blob/master/segmentation_models/losses.py) which is different with most defines I have saw, as below.
>def dice_loss(y_true, y_pred, smooth=1):
>    y_true_f = K.flatten(y_true)
>    y_pred_f = K.flatten(y_pred)
>    intersection = K.sum(y_true_f * y_pred_f)
>    return 1.- (2. * intersection + smooth) / (K.sum(y_true_f) + K.sum(y_pred_f) + smooth)

I couldn't understand this.

**Comment by LeeJayHui** [comment]
Hi, above all, Yasuo is one of my favorite, too.
I think you are right abour dice loss. For clarity, I have to re-explain your question. 
From your perspective, dice loss should be defined as follow:

> `def dice_loss(y_true, y_pred, smooth=1):`
        `y_true_f = K.flatten(y_true)`
        `y_pred_f = K.flatten(y_pred)`
        `intersection = K.sum(y_true_f * y_pred_f)`
        `return 1.- (2. * intersection + smooth) / (K.sum(y_true_f) + K.sum(y_pred_f) + smooth)`

But in the implementation provided by this repository, it appears in the form of `1-Fscore()`.
I totally agree with you. The dice loss here is different from the definition widely accepted.
@qubvel Sorry to bother you, but maybe a fix is needed about the implementation of dice loss.

**Comment by qubvel** [comment]
Hi guys, dice_score is equal to f1-score
Sources: 
https://en.m.wikipedia.org/wiki/S%C3%B8rensen%E2%80%93Dice_coefficient
https://en.m.wikipedia.org/wiki/F1_score

**Comment by qubvel** [comment]
![Screenshot_2019-12-21-12-21-47-189_com android chrome](https://user-images.githubusercontent.com/31920396/71306034-84790880-23ec-11ea-8209-8c1dab8be808.jpg)
![Screenshot_2019-12-21-12-21-36-493_com android chrome](https://user-images.githubusercontent.com/31920396/71306035-85119f00-23ec-11ea-8c63-030e28d0815e.jpg)

**Comment by qubvel** [comment]
If beta=1, you will get the same definition, so `f1-score == dice_score`

**Comment by LeeJayHui** [comment]
Thanks a lot to your attentive explanation. I was wrong about this, my bad.

**Comment by yasohasakii** [comment]
Thanks to your reply @qubvel , I think maybe I misunderstood the defination on Wikipedia because of `When applied to boolean data` , however, most labels we used in image segmentation are so called `one-hot` label ,means that they are boolean data. And your `DiceLoss` is trully works better than other dice loss defined ways.

**Comment by CevG33ko** [comment]
This could lead to confusions
https://arxiv.org/pdf/1807.10097.pdf
