### ISSUE TITLE
Multiclass segmentation

### ISSUE THREAD

**Issue by freddifederica** [qubvel/segmentation_models#28]
Firstly thanks a lot for the great repo!
`  I am trying to train my data to segment multiple classes and I have followed the code sample given:

    # prepare data
    preprocessing_fn = get_preprocessing('resnet34')
    x = preprocessing_fn(x)

    # prepare model
    model = Unet(backbone_name='resnet34', encoder_weights='imagenet')
    model.compile('Adam', 'binary_crossentropy', ['binary_accuracy'])

    # train model
    model.fit(x, y, epochs=100, batch_size=1)
    model.save('trained_mask.h5')`

My x is a list of (1, 256, 512, 3) (i.e. is an image of dimension 256x512) and my y is my segmentation mask. Currently I have successfully trained when the mask size is (1, 256, 512, 1), however I would like to adapt this code for multi-class-segmentation. Would that be possible? If yes, how? 

I have tried two different options so far:
- defined the label mask as a one-hot vector so that the y has now size (1, 256, 512, 13) (where 13 is the total number of classes considered to label).
     + This however fails with this error: 
ValueError: Error when checking target: expected sigmoid to have shape (None, None, 1) but got array with shape (256, 512, 13)

- so then given the error found I tried (probably naively) to use (1, 256, 512, 1) however setting each pixel of the mask with a number from 0 to 13 where 0 stands for unlabelled pixel and any other number is the desired class label. 
     + Despite this trains successfully, the result of testing is still a mask bounded to values between 0 and 1, so it does not allow multiple-class segmentation.

Could anyone show me what I am doing wrong and how I could solve the multi-class problem?

Thank you!

**Comment by qubvel** [comment]
Hi, @freddifederica 
Yes, multiclass segmentation is possible. Define the model as follows:
```python
# define model with output of N classes, where N > 1
model = Unet('resnet34', input_shape=(None, None, N), activation='softmax')

# for multiclass segmentation choose another loss and metric
model.compile('Adam', loss='categorical_crossentropy', metrics=['categorical_accuracy'])
```
I also recommend you to try another network architectures like FPN and PSPNet (they are more suitable for multiclass segmentation problems).

**Comment by freddifederica** [comment]
I have followed your suggestion and trained on FPN with:

```
# prepare data
preprocessing_fn = get_preprocessing('resnet34')
X = preprocessing_fn(X)
# prepare model
model = FPN('resnet34', classes=len(RGBdictionary), activation='softmax')
model.compile('Adam', loss='categorical_crossentropy', metrics=['categorical_accuracy'])

```

Trains smoothly and save the weights without any problem, however when I try to test and load the weights again I get this error:

```
File "segmentation-test.py", line 20, in <module>
    model = load_model('trained_mask.h5')
  File "/anaconda3/lib/python3.6/site-packages/keras/engine/saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "/anaconda3/lib/python3.6/site-packages/keras/engine/saving.py", line 225, in _deserialize_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/anaconda3/lib/python3.6/site-packages/keras/engine/saving.py", line 458, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/anaconda3/lib/python3.6/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/anaconda3/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "/anaconda3/lib/python3.6/site-packages/keras/engine/network.py", line 1022, in from_config
    process_layer(layer_data)
  File "/anaconda3/lib/python3.6/site-packages/keras/engine/network.py", line 1008, in process_layer
    custom_objects=custom_objects)
  File "/anaconda3/lib/python3.6/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/anaconda3/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 138, in deserialize_keras_object
    ': ' + class_name)
ValueError: Unknown layer: ResizeImage
```

Do you know what might be the issue? I simply imported `load_model` from `keras.models` and used the provided function to load the weights that I had trained on FPN. Did not have this issue when importing the weights I had saved using Unet 

Thanks

**Comment by qubvel** [comment]
Just write before loading model: `import segmentation_models`

**Comment by freddifederica** [comment]
I tried training and testing both on FPN and PSPNet however I got some issue when testing the results. In the case of the FPN I got as output results masks that only present 0 or 1 values and are not precise as the not match the training mask even when, despite defining the model activation layer as `activation='softmax'`.

These are my key lines used for the FPN model on training and the input X and y are the same I use to train on Unet (which trained and tested with good results given the same X and y). 
The input sizes are:
X - [n, H, W, 3]
y -[n, H, W, C]
where n is the number of images considered (i.e. data size) and the C is the total number of classes of the multi class problem.

```
from segmentation_models import FPN
from segmentation_models.backbones import get_preprocessing

# prepare data
preprocessing_fn = get_preprocessing('resnet34')
X = preprocessing_fn(X)

# prepare model
model = FPN('resnet34', classes=len(RGBdictionary), activation='softmax')
model.compile('Adam', loss='categorical_crossentropy', metrics=['categorical_accuracy'])

# train model
model.fit(X, y, epochs=1000, batch_size=2)
```


In the case of the PSPNet, instead, for the exact same X and y at testing I obtain some sort of rectangular patter which I really can't explain with some very defined an straight boundaries. Here however, I don't have the same problem of the outputs being only 0s or 1s. 
Even in this case I used the same code as above changing the model definition to 
`model = PSPNet('resnet34', classes=len(RGBdictionary), activation='softmax', input_shape=(output_height, output_width,3))`

This is an example of what I mean by "rectangular pattern":

<img width="578" alt="screenshot 2018-12-10 at 17 04 46" src="https://user-images.githubusercontent.com/37051452/49744808-ebbe9180-fc9d-11e8-87f9-09b254dfeb9e.png">
<img width="556" alt="screenshot 2018-12-10 at 17 04 34" src="https://user-images.githubusercontent.com/37051452/49744813-eeb98200-fc9d-11e8-8c8a-e538adf45a96.png">

Thanks for your help
