### ISSUE TITLE
ConcatOp : Dimensions of inputs should match

### ISSUE THREAD

**Issue by startupgurukul** [qubvel/segmentation_models#282]
Hi Pavel,
Thank you for open sourcing your work, while trying to train a custom dataset,  hit this issue, 

InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: ConcatOp : Dimensions of inputs should match: shape[0] = [1,256,48,64] vs. shape[1] = [1,288,48,63]
	 [[{{node decoder_stage1_concat_7/concat}}]]
	 [[metrics_8/f1-score/Mean_1/_48461]]
  (1) Invalid argument: ConcatOp : Dimensions of inputs should match: shape[0] = [1,256,48,64] vs. shape[1] = [1,288,48,63]
	 [[{{node decoder_stage1_concat_7/concat}}]]

As per the closed issue https://github.com/qubvel/segmentation_models/issues/273 which says width,height should be divisible by 32, and the data being passed is 320X320, aslo confirmed by assert below

assert train_dataloader[0][0].shape == (BATCH_SIZE, 320, 320, 3)
assert train_dataloader[0][1].shape == (BATCH_SIZE, 320, 320, n_classes)

Can you advice, 
Thanks in Advance.

**Comment by startupgurukul** [comment]
My mistake training data was correct, but validation data was not divisible by 32, Closing the issue

**Comment by maheeetaaa** [comment]
@startupgurukul I have the same issue, but I did not understand how you fixed it. Can you elaborate?

**Comment by svakln** [comment]
try using tf.expand_dims

**Comment by amenevatanparast** [comment]
hello every one
I Have exactly this problem for training model with other data set.
please if you solve that, help me :)

---------------------------------------------------------------------------------------------------------------------------- 
> Hi Pavel,
> Thank you for open sourcing your work, while trying to train a custom dataset, hit this issue,
> 
> InvalidArgumentError: 2 root error(s) found.
> (0) Invalid argument: ConcatOp : Dimensions of inputs should match: shape[0] = [1,256,48,64] vs. shape[1] = [1,288,48,63]
> [[{{node decoder_stage1_concat_7/concat}}]]
> [[metrics_8/f1-score/Mean_1/_48461]]
> (1) Invalid argument: ConcatOp : Dimensions of inputs should match: shape[0] = [1,256,48,64] vs. shape[1] = [1,288,48,63]
> [[{{node decoder_stage1_concat_7/concat}}]]
> 
> As per the closed issue #273 which says width,height should be divisible by 32, and the data being passed is 320X320, aslo confirmed by assert below
> 
> assert train_dataloader[0][0].shape == (BATCH_SIZE, 320, 320, 3)
> assert train_dataloader[0][1].shape == (BATCH_SIZE, 320, 320, n_classes)
---------------------------------------------------------------------------------------------------------------------------

**Comment by xqtbox** [comment]
Use
` A.Resize(320, 320)`
for validation

**Comment by MasoudAali** [comment]
> My mistake training data was correct, but validation data was not divisible by 32, Closing the issue

It might be a stretch, but I received a similar error in an image segmentation task because I was trying to resize the training images to 450X450 (450 is not a multiple of 32). I resolved the issue by changing the target size to 480X480 (480 is a multiple of 32). I hope it helps someone with my problem.

**Comment by khanfarhan10** [comment]
I was using PSPNet, and it only takes sizes as multiples of 48.

```
MAIN_SIZE_X = 528
MAIN_SIZE_Y = 528
def get_validation_augmentation():
    """Add paddings to make image shape divisible by 48"""
    """
    Also U can try  A.PadIfNeeded(MAIN_SIZE_X, MAIN_SIZE_Y)
    """
    test_transform = [
        A.Resize(MAIN_SIZE_X, MAIN_SIZE_Y)
    ]
    return A.Compose(test_transform)
```
