### ISSUE TITLE
issue for model.summary()

### ISSUE THREAD

**Issue by Fieldhunter** [qubvel/segmentation_models#286]
I use segmentation_models' vgg16 to see model.summary(),finding it's very differnet to keras.applications.vgg16.VGG16.Then I use the same download's VGG16 weights in these two ways,finding its work! So I'm confused that the same model in these two ways has different model.summary().I hope someone can give a reasonable explanation.

**Comment by JordanMakesMaps** [comment]
How is it different? It might be how each VGG implementation is built, whether it uses the Sequential or Functional API?

**Comment by Fieldhunter** [comment]
@JordanMakesMaps The model is built by keras.applications.vgg16.VGG16(), which summary() shows the end layer is 'block5_pool (MaxPooling2D) '. But the other model is built by sm.Unet('vgg16'), which summary() shows different result. I watch every layers in two models'summary(), finding sm.Unet's model include the keras.applications.vgg16.VGG16's model in the beginning part, and in the later part sm.Unet's model has other layers, such as 'center_block...' and 'decoder_stage...'. And in the end of model.summary(), two models have different params. In other models such as inception_v3 have similar situation. So I want to know why there is such a difference.

**Comment by JordanMakesMaps** [comment]
So I might be completely misunderstanding what's happening in your question, so bear with me 😅

The Keras implementation returns a VGG16 CNN (w/ or w/o the fully connected layers depending on if you include the top or not). When you use segmentation_model's implementation, you're getting back a UNet architecture with VGG16 as the encoder, which is then followed by the center and decoder block. When you use the Keras weights with the segmentation_model implementation, you're supplying the weights to *just* the encoder, and the fact that it doesn't throw an error means that @qubvel's code is consistent with Keras'.

If I completely missed your question, please add pictures to help illustrate 😃

**Comment by Fieldhunter** [comment]
@JordanMakesMaps Your answer didn't miss my question, and it was perfect. Before that, I was not very clear about how Unet works. After your answer, I have a very clear understanding. So thank you so much!:thumbsup::smiley:
