### ISSUE TITLE
load multiple segmentation models in the memory and run predicitions

### ISSUE THREAD

**Issue by kjodha** [qubvel/segmentation_models#287]
@qubvel Unable to load multiple segmentation models to run two different predictions on the same image.

**Comment by JordanMakesMaps** [comment]
See [here](https://github.com/keras-team/keras/issues/8538#issuecomment-358720718) for a conversation about the subject, it might help.

**Comment by kjodha** [comment]
@JordanMakesMaps Thank you for sharing the link. I wanted to load multiple models into the memory prior running any predictions, and I'd be running predictions on multiple threads at the same time. So, because I was loading the models on the main thread, it'd not let me run the predictions on a separate thread. But using model._make_predict_function() after loading the model helped resolve the issue.
