### ISSUE TITLE
Python 3.5 support?

### ISSUE THREAD

**Issue by kielnino** [qubvel/segmentation_models#30]
Thanks for this great repository.

Why is it rated for Python 3.6 and higher only?  The official Tensorflow-Docker-Container use Python 3.5. What do I need to change to make it compatible?

**Comment by qubvel** [comment]
Hi @kielnino 

Try to use it as it is. Install from repo (README). I use 'f' string formatting somewhere (python 3.6 feature), but cannot find it any more, may be I have already fixed that, but didn`n add 3.5 python support to pypi package.

**Comment by kielnino** [comment]
I found only two occurrences [here](https://github.com/qubvel/segmentation_models/blob/master/segmentation_models/linknet/blocks.py#L68) and [here](https://github.com/qubvel/segmentation_models/blob/master/segmentation_models/linknet/blocks.py#L98). After changing them it works fine on Python 3.5.

**Comment by amberhappy** [comment]
hi，can you tell me how to change the code to support python3.5?
now I have an error occurred:No module named "classification_models.model_factory"

**Comment by qubvel** [comment]
@amberhappy 
Python 3.5 is supported, check requirements installed (see requirements.txt).
