### ISSUE TITLE
Create masks for Multi-class segmentation model

### ISSUE THREAD

**Issue by kjodha** [qubvel/segmentation_models#300]
@qubvel : So, I've been using binary segmentation model for a while now, and it has been working fine for me. But, I'm not sure how do I get through creating a multiclass segmentation mask. I've got binary masks for every class separately, so should I create just one numpy array to stack them on top of each other and create a multi channel array, or should I annotate each mask as a separate class "0,1,2.." and merge them in one single channel array.

**Comment by JordanMakesMaps** [comment]
`should I create just one numpy array to stack them on top of each other and create a multi channel array`

I ran into the same question originally, *yes*.

This is the semantic segmentation form of one-hot encoding. Each channel within the 'image' represents a class, and within that channel the index is labelled with a 0 or 1 to denote. I store all my masks as numpy arrays and if you need to view them, simply use `np.argmax(mask, axis = 2)` with whatever display function you use.

Depending on how you make your masks, the `to_categorical()` function in Keras may or may not be useful to you when it comes to passing your mask to the model during training.

Here's an image that illustrates conceptually what's going on:
![one-hot-endcoded-example](https://user-images.githubusercontent.com/8714759/75387972-27994300-58b2-11ea-8717-170adb5e9c40.PNG)

**Comment by SreenijaK** [comment]
@kjodha what is the tool that you use for annotation of images?

**Comment by kjodha** [comment]
> @kjodha what is the tool that you use for annotation of images?

@SreenijaK I'm not using any tool to annotate the images, I already have a database of annotated images.

**Comment by kjodha** [comment]
> `should I create just one numpy array to stack them on top of each other and create a multi channel array`
> 
> I ran into the same question originally, _yes_.
> 
> This is the semantic segmentation form of one-hot encoding. Each channel within the 'image' represents a class, and within that channel the index is labelled with a 0 or 1 to denote. I store all my masks as numpy arrays and if you need to view them, simply use `np.argmax(mask, axis = 2)` with whatever display function you use.
> 
> Depending on how you make your masks, the `to_categorical()` function in Keras may or may not be useful to you when it comes to passing your mask to the model during training.
> 
> Here's an image that illustrates conceptually what's going on:
> ![one-hot-endcoded-example](https://user-images.githubusercontent.com/8714759/75387972-27994300-58b2-11ea-8717-170adb5e9c40.PNG)

@JordanMakesMaps Thank you for your response. I was able to train a model successfully for multiple classes with one hot encoded masks stacked on top of each other as shown in the image you provided. Closing the issue.

**Comment by kjodha** [comment]
@JordanMakesMaps Is there a simple way to merge these output multichannel array back to a single channel array as 0,1,2,3... for each class?

**Comment by JordanMakesMaps** [comment]
@kjodha 

`np.argmax(mask, axis = 2)`

This will give a you a single channel image, where each index has the class category value that was classified as.
