### ISSUE TITLE
Load data for backbone from file

### ISSUE THREAD

**Issue by harshnagarkar** [qubvel/segmentation_models#311]
I am using the FPN model from this library when I try to the run on a supercomputer, I don't have internet access to download the weight. I am using FPN with the backbone of efficient netb3. Instead of downloading the efficient data from the GitHub link is there any to load from the computer file.
@qubvel

**Comment by JordanMakesMaps** [comment]
Here are the weights that you can download directly:

https://github.com/qubvel/efficientnet/releases/

Then transfer them, along with all of your other files/scripts to your super computer to work offline.

**Comment by harshnagarkar** [comment]
Thanks. I just load them in encoder weights right.

**Comment by JordanMakesMaps** [comment]
Yup! You should be able to pass the weights path.

**Comment by rezabasiri** [comment]
Can you please specify where exactly you entered the local path?

**Comment by JordanMakesMaps** [comment]
```python
model = sm.Unet('resnet34', encoder_weights='weights//best_model.h5')
```
So you can replace `encoder_weights` with a local path if you want (maybe you've trained the same CNN architecture for image classification and you want to reuse it for semantic segmentation). 

If you're trying to load the weights for the _entire_ model then you just create the model and load the weights like normal:

```python
model = sm.Unet('resnet34')
model.load_weights('best_trained_model.h5')
```

**Comment by rezabasiri** [comment]
Thank you. :)
