### ISSUE TITLE
Now with Noisy-Student weights for EfficientNet encoders!

### ISSUE THREAD

**Issue by JordanMakesMaps** [qubvel/segmentation_models#312]
Howdy people,

I saw an [issue ](https://github.com/qubvel/efficientnet/issues/96) on @qubvel's other repo for EfficientNet asking for the Noisy-Student weights. So if you want to access those weights for your encoder in this repo, just go over to that repo and update with pip!

Then when creating a segmentation model, change the `encoder_weights` parameter from `imagenet` to `noisy-student`

[Here's ](https://github.com/qubvel/efficientnet/commit/6ceca713c1186168f41a7a628e4d6e2fdc4aa7ef)the commit details

**Comment by tonyboston-au** [comment]
Hi @JordanMakesMaps 
Just tried this (after doing a pip install on EfficientNet) with no luck. Must be doing something simple wrong. Error is:

ValueError: The `weights` argument should be either `None` (random initialization), `imagenet` (pre-training on ImageNet), or the path to the weights file to be loaded.

Thanks
