### ISSUE TITLE
Second run getting low "not reasonable" results

### ISSUE THREAD

**Issue by BarakBat** [qubvel/segmentation_models#34]
Hi, I ran the model with Resnext50, got a normal result, everything was great.
The second time, I ran the model with Resnext50 (even with exactly the same hyperparameters) I'm getting a very low result, I mean my dice_coef is 0.042 after 20 epochs, in the first run it was 0.3.
It happened also with resnet50 and resnet34.

Someone have any Idea what's wrong and what am I missing?!

Thanks!

**Comment by qubvel** [comment]
Hi, @BarakBat 
Have no idea what may be wrong.. What about third time? Is error reproducible? Did you run model training in Jupyter or in python script?
