### ISSUE TITLE
Can I apply the preprocessing to the data generator directly?

### ISSUE THREAD

**Issue by bhomaidan1990** [qubvel/segmentation_models#343]
Hi, I have a question regarding the preprocessing of the input, **can I apply that directly to the data generator?**
```
import segmentation_models as sm
BACKBONE = 'efficientnetb7'
preprocess_input = sm.get_preprocessing(BACKBONE)
train_generator     = preprocess_input(train_generator)
```

**Comment by JordanMakesMaps** [comment]
No. But you could just put `preprocess_input()` within the definition of your `train_generator` so that whenever you get a batch, one of the steps is that the images are ran through the `preprocess_input()`.

**Comment by bhomaidan1990** [comment]
Thanks for help
