### ISSUE TITLE
Adding scSE blocks to the architecture.

### ISSUE THREAD

**Issue by Venka97** [qubvel/segmentation_models#35]
Hi,

How can I modify the architecture that you have provided?  I'd like to add scSE blocks as well to the encoder/decoder. I know I can change the input and output using Keras Model class and using Model(inp=x,out=y) but how do I change the layers in-between?

**Comment by qubvel** [comment]
Hi @Venka97,
Look at [this](https://github.com/ybabakhin/kaggle_salt_bes_phalanx/tree/master/bes/segmentation_models) modification of the winner of Kaggle Salt Identification challenge
