### ISSUE TITLE
Working of Code for Images with Multiple Channels (more than 3(rgb))

### ISSUE THREAD

**Issue by ArvindSharma18** [qubvel/segmentation_models#353]
Hello! The code seems to work perfectly for 3 band images. I hope you can throw some light on usage of code for Images with multiple band i.e More than 3 usual band(RGB). 
What changes should I make to accommodate images with more than 3 band images because when I tired to run the code with say 6 band image,  I am getting this error:
ValueError: Error when checking input: expected data to have shape (None, None, 3) but got array with shape (320, 320, 6)
Is there any backbone available that can help me with Multiple Band problem?

**Comment by qubvel** [comment]
Hi, this case is described in docs!
