### ISSUE TITLE
Allow for other input depths than 3

### ISSUE THREAD

**Issue by AlfTetzlaff** [qubvel/segmentation_models#36]
Hi, this is a feature request:
I'm interested in using a different number of input channels, let's say 5. This could be achieved by reshaping using a 1x1 convolution or by adapting the number of filters in the first convolution. In the latter case there would be no pretrained weights available or one would have to copy the weights from one of the pretrained filters to the added filters for later fine-tuning, which might even be preferable.

Kind regards and a happy new year!

**Comment by AlfTetzlaff** [comment]
Yes - and sorry for not reading before typing...
But there is another option, which does not require training from scratch: One could in theory use the pretrained model and just change the first layer.

Example:
Let's suppose one wants to process remote sensing data of the form (blue, green, red, near IR).
1) Initialize new model with different number of filter depth (here four) in first layer.
2) Copy weights for each filter channel from the pretrained model into the corresponding channel of the newly instantiated model.
3) What to do with the near IR channel? Here one could simply copy the weights from the red channel for later fine-tuning.

I expect this procedure to yield better results than just mapping to three channels by a 1x1 conv, but didn't test it yet. Perhaps it's also too much effort for a too special use case, I don't know...

**Comment by qubvel** [comment]
Yes, your approach may be useful, but keras does not support loading weights starting from second/non-first layer :disappointed: 

So the way I see here is:
1) create model `one` with 3 channels and load `imagenet` weights
2) create same model `two` but with N channels and with random weights initialization
3) transfer weights from model `one` to model `two` iterating by layers (may be very time consuming)

If you have any other suggestions, you are welcome. Moreover, PRs are appreciated :smile:

**Comment by AlfTetzlaff** [comment]
That is more or less, what I had in mind. If I find the time, I will look into it in detail.

**Comment by JordanMakesMaps** [comment]
If anyone is looking to do this, the code is something like:

```python
BACKBONE = 'somebackbone'

model_w_weights = sm.Unet(input_shape = (None, None, 3), 
                backbone_name = BACKBONE, 
                encoder_weights = 'imagenet')


model = sm.Unet(input_shape = (None, None, 5), 
                    backbone_name = BACKBONE, 
                    encoder_weights = None)

for layer_index in range(len(model_w_weights.layers)):
    if(layer_index < 2 ): continue
    print(layer_index, model_w_weights.layers[layer_index].name, model.layers[layer_index].name)
    model.layers[layer_index].set_weights(model_w_weights.layers[layer_index].get_weights())

del model_w_weights
```
