### ISSUE TITLE
How to train with GPU

### ISSUE THREAD

**Issue by blasco** [qubvel/segmentation_models#364]
Does the provided multi-class example work with a gpu? What changes do I need to apply? from what I see there is a different tensor flow package for gpu.

**Comment by JordanMakesMaps** [comment]
You don't. Just make sure you have the right Tensorflow-GPU and Keras-GPU packages installed as stated in the readme and make sure you have cuda and all of the right drivers for your NVIDIA gpu installed on your machine.

**Comment by blasco** [comment]
You are right, it was a little bit painful to configure, but it's working fantastic. Thank you
