### ISSUE TITLE
where should I put the downloaded weight file?

### ISSUE THREAD

**Issue by Gatsby-2019** [qubvel/segmentation_models#366]
directly download the 'imagenet' weight file is extremely slow for my network condition. but i have downloaded it from other sources, but can i just put it into the work paths for the packages to load the  weight automatically? and where are the work path for weight file?

**Comment by Gatsby-2019** [comment]
could u please help on how to load checkpoint or weight for models?

**Comment by Gatsby-2019** [comment]
found the parameter weights – optional, path to model weights. solved my problem.

**Comment by iwaitu** [comment]
> found the parameter weights – optional, path to model weights. solved my problem.

how do you solve this problem ?
