### ISSUE TITLE
Prediction on images without masks

### ISSUE THREAD

**Issue by Alex-259** [qubvel/segmentation_models#373]
Hello,

first of all, @qubvel thanks for the good site and also good explanations.
I use the code for detecting damages in a production line. Training and testing the UNET model as described in the 
Jupyter Notebooks works well for my case, when i have the images as well as the annotations/masks of them.

Now i wonder if there is an easy way to change for example the binary segmentation (camvid).ipynb file to
do the prediction without knowing the masks of the images.

I want to apply the trained models on new images without any masks and find the damages inside the images.

Can somebody help me?

**Comment by JordanMakesMaps** [comment]
Once you have a trained model then just feed it a novel image:
```python
img = io.imread(file) # novel image
img = preprocess_input(img) # use the preprocessing input method based on the backbone you used
mask = model.predict(np.expand_dims(img, axis = 0)).squeeze() # change the shape to (1 H, W)
mask.shape() # (H, W, C)
io.imshow(np.argmax(mask, axis = 2)) # shows (H, C)
```

**Comment by Alex-259** [comment]
Thank you @JordanMakesMaps  it works.
