### ISSUE TITLE
ModuleNotFoundError: No module named 'classification_models'

### ISSUE THREAD

**Issue by sklipnoty** [qubvel/segmentation_models#38]
Just cloned.

**Comment by qubvel** [comment]
`pip install image-classifiers==0.1.0rc0`

**Comment by GusRoth** [comment]
but I still meet the problem after pip install image-classifiers

**Comment by GusRoth** [comment]
please help me @ @qubvel

**Comment by qubvel** [comment]
Hi @GusRoth 
Try to use PyPI version

**Comment by GusRoth** [comment]
> Hi @GusRoth
> Try to use PyPI version

thank you!
