### ISSUE TITLE
module 'keras.utils' has no attribute 'generic_utils'

### ISSUE THREAD

**Issue by kevin-scaria** [qubvel/segmentation_models#398]
I have latest tensorflow and keras. I am using the segmentation_model package in colab.

When I import using the code:

import segmentation_models as sm, 
I get the following error.

**Comment by Kevin43614** [comment]
from keras.utils import generic_utils

You can try add this in your code

**Comment by kevin-scaria** [comment]
Thanks alot @Kevin43614 it worked.
