### ISSUE TITLE
Clarification regarding code multiclass segmentation (camvid)

### ISSUE THREAD

**Issue by jayaBalaR** [qubvel/segmentation_models#402]
Hi 

Could you please help me understand what is the purpose of using denormalize for the masks in the multiclass segmentation code?

Thank you

![image](https://user-images.githubusercontent.com/21074002/92492339-dbd83680-f210-11ea-8d8f-663936d0ddcf.png)

**Comment by JordanMakesMaps** [comment]
Is it used for the masks as well as the images? If so, I think it might just be a typo. Masks are categorical and shouldn't be manipulated using math (if you plan to resize masks, use nearest neighbor interpolation for this reason).

**Comment by jayaBalaR** [comment]
Okay thanks much for the clarification.
Cheers
