### ISSUE TITLE
ValueError: Dimensions must be equal, but are 20 and 3 for 'loss/softmax_loss/mul_4' (op: 'Mul') with input shapes: [20], [3].

### ISSUE THREAD

**Issue by BrunoKrinski** [qubvel/segmentation_models#416]
I followed this colab to train on my dataset. 
https://github.com/qubvel/segmentation_models/blob/master/examples/multiclass%20segmentation%20(camvid).ipynb

My code is the same here but I'm getting this annoying error:
ValueError: Dimensions must be equal, but are 20 and 3 for 'loss/softmax_loss/mul_4' (op: 'Mul') with input shapes: [20], [3].

20 is the number of classes I have.

it seems that it occurs when I call: model.compile(optim, total_loss, metrics)

Traceback (most recent call last):
  File "main.py", line 204, in <module>
    model.compile(optim, total_loss, metrics)

I'm useing tensorflow 1.13.1

Someone knows what's happening? thanks!

**Comment by BrunoKrinski** [comment]
I found the problem.

**Comment by cspearl** [comment]
> I found the problem.

Hi, I am facing the same issue. If you could tell what solved your issue. Thanks!

**Comment by BrunoKrinski** [comment]
Sorry, but I can't remember how I solve this. Also, I'm using the Pytorch version of this framework. Also, sorry the delay to reply.
