### ISSUE TITLE
Any way to get per class IoU scores?

### ISSUE THREAD

**Issue by WeiChihChern** [qubvel/segmentation_models#447]
As title, I've been searching for this but didn't get related info.

Also tried to implement one but the final number is a little deviated from what mIoU score that `scores = model.evaluate_generator(test_dataloader)` calculated.

For example, if I have 4 classes of [background, car, pedestrian, bird], instead of just a mIoU, I would like to know each class's IoU score to know how they perform. Thanks.

**Comment by juanma9613** [comment]
This is my workaround,

Just instantiate three different metrics, one for each class and pass the class_indexes parameter.

iou_car =  IOUScore( threshold=0.5,  class_indexes=0)
iour_pedestrian =  IOUScore( threshold=0.5,  class_indexes=1)
iou_bird =  IOUScore( threshold=0.5,  class_indexes=2)

**Comment by WeiChihChern** [comment]
@juanma9613 Thanks for the workaround. I tried it, but I keep getting the error of 

> InvalidArgumentError: cannot compute Mul as input #1(zero-based) was expected to be a double tensor but is a float tensor [Op:Mul]

The error line came from:

```
~/.local/lib/python3.6/site-packages/segmentation_models/base/functional.py in iou_score(gt, pr, class_weights, class_indexes, smooth, per_image, threshold, **kwargs)
     91 
     92     # score calculation
---> 93     intersection = backend.sum(gt * pr, axis=axes)
     94     union = backend.sum(gt + pr, axis=axes) - intersection
```


I tried to convert both pr & gt to float32 and float64, but didn't work out. Any idea? Thanks.

**Comment by juanma9613** [comment]
I had the same error, what I did was to convert both of them outside of the metric to float32.

**Comment by WeiChihChern** [comment]
It worked out, thanks!
