### ISSUE TITLE
How to handle this warning???

### ISSUE THREAD

**Issue by sumeetssaurav** [qubvel/segmentation_models#45]
Could you please look at this warming and suggest what could be done in order to use the keras version of the pre-trained ResNeXt models. Since you model and the keras model are not at all compatible.

""Current ResNext models are deprecated, use keras.applications ResNeXt models""

Thanking You

**Comment by qubvel** [comment]
Hi @sumeetssaurav ,
Warning raised by image-classifiers library used for backbones. However keras resnext models is not possible to initialize with (None,None, N) shape, that is why I decide to use previous version of model, which was converted from MXNet. Dont worry, I will remove this warning.
