### ISSUE TITLE
documentation for loading the coco format custom dataset into model

### ISSUE THREAD

**Issue by codePerfectPlus** [qubvel/segmentation_models#454]
There is a missing tutorial on loading the coco format custom dataset into the model.

Thanks

**Comment by JordanMakesMaps** [comment]
You can use [LabelMe](https://github.com/wkentaro/labelme), which has a few shape -> mask [functions](https://github.com/wkentaro/labelme/blob/master/labelme/utils/shape.py) that uses `shapely`.
