### ISSUE TITLE
Error while importing "from segmentation_models import FPN" or any other model 

### ISSUE THREAD

**Issue by Ethiral** [qubvel/segmentation_models#46]
While importing FPN or any other available model I get the error :f'Conv2DTranspose support only upsample_rate=(2, 2), got {upsample_rate}'). Could you please look into this.
Tensorflow version:1.12
Keras version:2.2.4
Thank you!!

**Comment by qubvel** [comment]
Hi @Ethiral 
Works correctly for me:
```bash
$ docker run -it  tensorflow/tensorflow:latest-py3 bash
$ apt-get update
$ apt-get install git
$ pip install git+https://github.com/qubvel/segmentation_models
$ python -c "from segmentation_models import FPN"
```
Try to install lib from git repo `pip install git+https://github.com/qubvel/segmentation_models`

**Comment by Ethiral** [comment]
Hello @qubvel  installing lib from git repo worked .
Thanks a lot
