### ISSUE TITLE
Make this repo pip installable

### ISSUE THREAD

**Issue by yassineAlouini** [qubvel/segmentation_models#5]
For that, add a `setup.py` file. 

Here is a link to a great guid on how to do it: https://github.com/kennethreitz/setup.py. 

I can make a PR if you don't have time. Let me know and thanks again for creating this repo. :+1:

**Comment by qubvel** [comment]
Thanks for nice tutorial, now you can install it via pip `$ pip install segmentation_models`

**Comment by yassineAlouini** [comment]
Awesome. Thanks a lot. 😸
