### ISSUE TITLE
Loading the trained model

### ISSUE THREAD

**Issue by Ethiral** [qubvel/segmentation_models#50]
I trained a FPN model with vgg16 backbone for multi class segmentation(classes=3).While loading the trained model I get the error: "ValueError: Unknown layer: ResizeImage".
Thank you

**Comment by qubvel** [comment]
ResizeImage is a custom layer. Just import segmentation_models before loading model.

**Comment by Ethiral** [comment]
This works out .Thanks a lot @qubvel
