### ISSUE TITLE
how to trian non-square image with Unet? 

### ISSUE THREAD

**Issue by Suzan009** [qubvel/segmentation_models#502]
My image sizes are **670**, **460**, and divisible by **32** but yet I'm facing a concatenation error with unet. 

https://github.com/qubvel/segmentation_models/blob/94f624b7029deb463c859efbd92fa26f512b52b8/segmentation_models/models/unet.py#L183

I defined my model as follows

```
sm.Unet('efficientnetb5', 
                input_shape=(670, 460, 3),
                classes=10, 
               activation=activation)
```

```
ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concat axis.
````

How to solve this?

**Comment by Suzan009** [comment]
@qubvel

**Comment by qubvel** [comment]
Sorry, 670 is not divisible by 32
