### ISSUE TITLE
Ignore labels in semantic segmentation

### ISSUE THREAD

**Issue by ajuric** [qubvel/segmentation_models#52]
Is it possible to specify the ignore label for semantic segmentation models?

The purpose is to not use the ignore label in calculating the loss.

**Comment by qubvel** [comment]
Hi @ajuric 
Specify labels you need and model will not learn for others
e.g. you have labels for roads and buildings, but you can provide masks only for roads, another pixels mark as background

**Comment by ajuric** [comment]
Do you have some methods where these ignore labels (background) is specified or? I didn't get it...

**Comment by qubvel** [comment]
Hi, @ajuric 
I`m not sure I understand you correctly, please describe your case more clear.
