### ISSUE TITLE
ValueError: input shape

### ISSUE THREAD

**Issue by Bornlex** [qubvel/segmentation_models#58]
Hello,

Here is the code I have:
`model = segmentation_models.Unet(backbone_name='vgg19', encoder_weights='imagenet', input_shape=images[0].shape)
model.compile('Adam', 'binary_crossentropy', ['binary_accuracy'])
model.fit(images, seg_maps, epochs=2)`

And I get the following error:

> ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concat axis. Got inputs shapes: [(None, 36, 24, 512), (None, 37, 25, 512)]

Shapes are:
- images: (600, 400, 3)
- seg_maps: (600, 400, 1)

Thank you for you help on this really nice project.

**Comment by qubvel** [comment]
Input size should be divisible by 32
