### ISSUE TITLE
NCHW supports

### ISSUE THREAD

**Issue by Tyler-D** [qubvel/segmentation_models#69]
Hi @qubvel, I've built up a pipeline from training to integrating the trained model to TensorRT. And in my situation, an UNet + ResNet34 inference performance boost from 54ms/frame to 7ms/frame on P40 GPU. But to reach that point, I have to convert model of NHWC to NCHW cause there exists incompatibility between NHWC model and TensorRT parser. 

So I'm wondering if it is possible to add NHWC support here and so on so that the model can be easily leveraged by inference framework TensorRT.

**Comment by qubvel** [comment]
Hi @Tyler-D 
Yes it can be a good feature, however it requires changes in `classifiers` also.
I use tensoflow-serving and for me it is `ok` to have NHWC format). 

I don't think I'll be able to implement it soon. 
But you always can make a PR :smiley:

**Comment by mitsuix** [comment]
> Hi @qubvel, I've built up a pipeline from training to integrating the trained model to TensorRT. And in my situation, an UNet + ResNet34 inference performance boost from 54ms/frame to 7ms/frame on P40 GPU. But to reach that point, I have to convert model of NHWC to NCHW cause there exists incompatibility between NHWC model and TensorRT parser.
> 
> So I'm wondering if it is possible to add NHWC support here and so on so that the model can be easily leveraged by inference framework TensorRT.

I'm trying to use TensorRT. but I met some problems, how did you manage it?
Any suggestions?
Thanks a lot~

**Comment by Tyler-D** [comment]
@mitsuix , For TensorRT problem,  I think you could refer to official documentation of TRT at https://docs.nvidia.com/deeplearning/sdk/ to find solution.  If you're still blocked you could ask question in https://devtalk.nvidia.com/default/board/304/tensorrt/.

**Comment by mitsuix** [comment]
> @mitsuix , For TensorRT problem, I think you could refer to official documentation of TRT at https://docs.nvidia.com/deeplearning/sdk/ to find solution. If you're still blocked you could ask question in https://devtalk.nvidia.com/default/board/304/tensorrt/.

Thanks for your suggestion~
