### ISSUE TITLE
Running on a data without test labels

### ISSUE THREAD

**Issue by absagargupta** [qubvel/segmentation_models#70]
Hello there

Suppose I have trained my model on a dataset having the images as well as masks in the training as well as test set (Cityscape dataset). Is it possible that after training it on the (cityscape) dataset, I run it for creating masks of MSMT17_V2 image dataset? If yes what all changes should I do? Thank you well in advance for the reply :-)

**Comment by qubvel** [comment]
Hi, @absagargupta 
You can ake prediction on any images/any dataset (make sure to preprocess them same as in training stage), but model will produce label it have been trained on.

**Comment by absagargupta** [comment]
Thank you so much for the prompt reply. In case I need just the labels of people and the background what changes should I take care of?

**Comment by qubvel** [comment]
Suppose you have trained you model for `C`=10 classes, where value `3` is people class.
Output of network will be a tensor `output` with shape (N, H, W, 10).
To get mask of people class:
`mask = (np.argmax(output, axis=-1) == 3)`

**Comment by absagargupta** [comment]
Thank you. :-)
