### ISSUE TITLE
Read data using flow from directory

### ISSUE THREAD

**Issue by ramesh8v** [qubvel/segmentation_models#75]
Hello,
I'm wondering whether it's possible to load data using Keras flow_from_directory generator? I have thousands of training and test images, so loading everything into memory is not possible.

**Comment by qubvel** [comment]
Hi, @ramesh8v 
Yes it is possible, define your generator and use `model.fit_generator(...)`

**Comment by ramesh8v** [comment]
Hi @qubvel 

Thanks! How to run this step: 
```
# preprocess input
x_train = preprocess_input(x_train)
x_val = preprocess_input(x_val)
```

**Comment by qubvel** [comment]
keras generator has keyword argument preprocessing function

**Comment by ramesh8v** [comment]
Thanks @qubvel
