### ISSUE TITLE
Selecting backbone feature layers

### ISSUE THREAD

**Issue by mkisantal** [qubvel/segmentation_models#76]
Hi @qubvel, thank you for this repo!

I'm trying to find some information on how backbone feature layers are selected in an U-Net. E.g.:

    'resnet18': ('stage4_unit1_relu1', 'stage3_unit1_relu1', 'stage2_unit1_relu1', 'relu0')

in backbone `DEFAULT_FEATURE_LAYERS`.  The original U-Net paper didn't use pre-trained backbones, so it's not discussed there.

Can you point me to some resources where feature layer selection is described? Or what was your approach for selecting feature layers in the different backbone architectures?

**Comment by qubvel** [comment]
Hi, @mkisantal 
Logic is quite simple, take the output of the deepest feature layer for each spatial resolution

**Comment by mkisantal** [comment]
Thanks!
