### ISSUE TITLE
Something error with load_model

### ISSUE THREAD

**Issue by actionLUO** [qubvel/segmentation_models#79]

**Comment by actionLUO** [comment]
when i use Unet backbone and load_model, i met with SystemError: unknown opcode error, please help me!

**Comment by qubvel** [comment]
Hi @actionLUO 
check that python version is the same, sometimes it happens when you train model with python3.5 and load in 3.6

**Comment by actionLUO** [comment]
@qubvel Thanks， really related to the version!!!

**Comment by actionLUO** [comment]
solved the problem...
