### ISSUE TITLE
Is there any way to work with this if the image dimensions are 4000x6000x3 ?

### ISSUE THREAD

**Issue by andohuman** [qubvel/segmentation_models#81]
I'm trying to work on a segmentation task where the image dimensions are 4000x6000. Is there any way I can work with them without having to downsample the original images ?

I am not able to initialize any of the 4 models with that input shape. 

Any suggestions are welcome. 

(I tried with all the four models and the backbone resnet34)

**Comment by qubvel** [comment]
Hi, @andohuman 
You can crop your image to smaller ones, and train model on crops.
