### ISSUE TITLE
Problem with shape attribute

### ISSUE THREAD

**Issue by rkdx007** [qubvel/segmentation_models#82]
I am just trying out the working of all the models, hence I am using randomly generated data as
```
test_images = []
labels = []
for i in range(100):
    test_images.append(np.random.rand(200,200,3))
    rand = np.random.randint(10,size = 200*200)
    rand.reshape(rand.shape[0],1)
    labels.append(rand) 
test_images = np.array(test_images)
labels = np.array(labels)
x_train, x_val, y_train, y_val = train_test_split(test_images, labels, test_size=0.33, random_state=42)
y_train = to_categorical(y_train)
y_val = to_categorical(y_val)
```
But I am getting an error as follows:

```
Traceback (most recent call last):
  File "test.py", line 54, in <module>
    validation_data=(x_val, y_val),
  File "/home/rishav/.local/lib/python3.6/site-packages/keras/engine/training.py", line 952, in fit
    batch_size=batch_size)
  File "/home/rishav/.local/lib/python3.6/site-packages/keras/engine/training.py", line 789, in _standardize_user_data
    exception_prefix='target')
  File "/home/rishav/.local/lib/python3.6/site-packages/keras/engine/training_utils.py", line 128, in standardize_input_data
    'with shape ' + str(data_shape))


ValueError: Error when checking target: expected sigmoid to have 4 dimensions, but got array with shape (67, 40000, 10)
```

can you please help me out in this?

**Comment by qubvel** [comment]
Hi @rkdx007 
This is Image segmentation models, your data should be 4D tensors with shape (NUM_IMAGES, IMAGE_HEIGHT, IMAGE_WIDTH, IMAGE_CHANNELS)

**Comment by rkdx007** [comment]
Hi @qubvel 
Yeah, I understand that and hence my test_images array has a shape (NUM_IMAGES,200,200,3), but the corresponding label matrix will have a shape (NUM_IMAGES,200,200) because the label will be same across the 3 channels right? 
Sorry if the question seems silly, have just started working in this field. And thanks for your quick response. :-)

**Comment by qubvel** [comment]
@rkdx007 
The label does not depend on the number of channels of data. In case of binary segmentation (1 target class + background) add dummy channel dimension `1` (NUM_IMAGES, 200, 200, **1**).
**Note**: shape 200 is not valid, it should be divisible by 32 e.g. 256/128/etc.

You are welcome)

**Comment by rkdx007** [comment]
Thanks! It's working perfectly fine now.
