### ISSUE TITLE
IOU metric score is not correct

### ISSUE THREAD

**Issue by margokhokhlova** [qubvel/segmentation_models#84]
Hi!
I think there is an error in the jaccard index computation...
There is a case when there are no ground-truth positive class and no positive prediction, then the score should be 1.
However, the metric gives the score equal to zero, and then the average score is lower than it should be.
I am talking about this function:
iou_score(gt, pr, class_weights=1., smooth=SMOOTH, per_image=True)
And in wiki, the definition of the Jaccard index:
(If A and B are both empty, we define J(A,B) = 1.)

**Comment by qubvel** [comment]
hi @margokhokhlova 
Yes, you can increase SMOOTH value to make it equal to 1. Actually it happens because predicted values small but not 0 (e.g. 1e-7). Another way to handle it - round predictions.

**Comment by margokhokhlova** [comment]
Thank you for the quick reply!
Yes, I see now, it was just a way too low constant value.
