### ISSUE TITLE
a question about changes in unet architecture

### ISSUE THREAD

**Issue by margokhokhlova** [qubvel/segmentation_models#85]
Hello!
thank you for the code!
Would really appreciate your help here.
I want to modify the model (unet) and use the following parameter as the list of encoder filters:
decoder_filters=(**512**, 256, 128, 64)
The corresponding backbone is resnetXt50.
The default skip connections are:
('stage4_unit1_relu1', 'stage3_unit1_relu1', 'stage2_unit1_relu1', 'relu0')

I guess, I need to modify them to match my decoder filters, and I tried to that following the recommendations (ncoder_features – a list of layer numbers or names starting from top of the model. Each of these layers will be concatenated with corresponding decoder block.) but it doesn't seem to work. Please, if you can give an example of the parameters passed to the network for the mentioned case, it will be highly appreciated.

**Comment by qubvel** [comment]
Hi @margokhokhlova 
1. Keras automatically calculate input channels, so you can take any architecture and dont think about skip connections shape.
2. `decoder_filters` - number of filter in decoder blocks, length should be 5 -> (512, 256, 128, 64, **32**)

**Comment by margokhokhlova** [comment]
>**< Thank you for your answer!
I was trying to make it 4 blocks and not 5 to try to gain some more accuracy but I might be missing smth. It works with  (512, 256, 128, 64, 32), so I will check the accuracy on my data.

**Comment by qubvel** [comment]
Encoder has 5 downalsampling stages -> decoder should have 5 upsampling stages to have same spatial resolution of output. If you make 4 blocks - output mask will be two times smaller on each side than input image.

**Comment by margokhokhlova** [comment]
I see, thank you!
