### ISSUE TITLE
load_model issue

### ISSUE THREAD

**Issue by panakouris** [qubvel/segmentation_models#86]
Hi,
First of all thanks for the great work. I trained a FPN model, with Resnext50 as backbone, for multiclass image segmentation.  I saved the model using ```model.save()``` but when I try to retrieve in order to evaluate the performance on a new test dataset, I get a ```ValueError: Unknown layer: Slice```. Has anyone else faced a similar problem?

**Comment by panakouris** [comment]
Ok found it. In order to load the particular model, I did the following and it worked.
```
from segmentation_models.common.layers import ResizeImage
from classification_models.common.blocks import Slice
model = load_model(FILENAME_MODEL, custom_objects={'Slice': Slice, 'ResizeImage': ResizeImage})
```

**Comment by qubvel** [comment]
You should be able to load model just after this line of code:
```import segmentation_models```
Layers will be registered as custom objects in global keras registry.

**Comment by sarahESL** [comment]
Thanks a lot @qubvel , I was having the same issue and importing the library fixed it. Would be great if you could add this to the README so that in future people won't have to search in the issues to find this solution.
