### ISSUE TITLE
NameError: name 'get_prepocessing' is not defined

### ISSUE THREAD

**Issue by zthreefires** [qubvel/segmentation_models#87]
I can't run the sample code from https://segmentation-models.readthedocs.io/en/latest/tutorial.html, the error information is just like the title.
I only alter the path of input like this,
```  python
x_train, y_train, x_val, y_val = load_data("/Volumes/NT/code/data/dataset/train/src",
                                            "/Volumes/NT/code/data/dataset/train/label",
                                            "/Volumes/NT/code/data/dataset/test/src",
                                            "/Volumes/NT/code/data/dataset/test/label")
```
the whole error is this:
UserWarning: Current ResNext models are deprecated, use keras.applications ResNeXt models  warnings.warn('Current ResNext models are deprecated, '
Traceback (most recent call last):
  File "/Users/zhangsanhuo/Desktop/code/test.py", line 7, in <module>
    preprocess_input = get_prepocessing(BACKBONE)
NameError: name 'get_prepocessing' is not defined
waiting for your reply,thanks.

**Comment by qubvel** [comment]
Hi,
There is a typo: get_preprocessing (missed *r* letter)

**Comment by zthreefires** [comment]
> Hi,
> There is a typo: get_preprocessing (missed _r_ letter)

sorry,thanks.

**Comment by zthreefires** [comment]
another question, how can I use the load_data function? 
i know this is stupid, but i'm a beginner.
I need to do some work to graduate.

**Comment by Diyago** [comment]
You can start with smth like this:

``` python 
import os
import numpy as np
from skimage.io import imread
from skimage import transform
from cv2 import resize
from keras.preprocessing.image import load_img

data_dir = './data_objects'

def load_data(root_dir):
    data = []

    for stage in ['train']:
        directory = os.path.join(root_dir,  'images')
        file_names = [filename.replace('jpg' , 'png') for filename in os.listdir(directory)]
        fps = [os.path.join(directory, filename) for filename in os.listdir(directory)]
        for content in ['images', 'segmentation']:
            # construct path to each image
            directory = os.path.join(root_dir,  content)
            
            if content != 'images':
                fps = [os.path.join(directory, filename) for filename in file_names]
                
            # read images
            images = [imread(filepath)/255 for filepath in fps]
 
            # if images have different sizes you have to resize them before:
            resized_images = [resize(image, (256, 256)) for image in images]
            
            # stack to one np.array 
            np_images = np.stack(resized_images, axis=0)
            
            data.append(np_images)
            
    return data
x_train, y_train  = load_data(data_dir)
```

**Comment by zthreefires** [comment]
> You can start with smth like this:
> 
> ```python
> import os
> import numpy as np
> from skimage.io import imread
> from skimage import transform
> from cv2 import resize
> from keras.preprocessing.image import load_img
> 
> data_dir = './data_objects'
> 
> def load_data(root_dir):
>     data = []
> 
>     for stage in ['train']:
>         directory = os.path.join(root_dir,  'images')
>         file_names = [filename.replace('jpg' , 'png') for filename in os.listdir(directory)]
>         fps = [os.path.join(directory, filename) for filename in os.listdir(directory)]
>         for content in ['images', 'segmentation']:
>             # construct path to each image
>             directory = os.path.join(root_dir,  content)
>             
>             if content != 'images':
>                 fps = [os.path.join(directory, filename) for filename in file_names]
>                 
>             # read images
>             images = [imread(filepath)/255 for filepath in fps]
>  
>             # if images have different sizes you have to resize them before:
>             resized_images = [resize(image, (256, 256)) for image in images]
>             
>             # stack to one np.array 
>             np_images = np.stack(resized_images, axis=0)
>             
>             data.append(np_images)
>             
>     return data
> x_train, y_train  = load_data(data_dir)
> ```

thank you very much!!!
