### ISSUE TITLE
Pretrained models - COCOStuff

### ISSUE THREAD

**Issue by Prakashvanapalli** [qubvel/segmentation_models#92]
Hi @qubvel , Is there by any chance we have pretrained weights available for [cocostuff](https://github.com/nightrome/cocostuff), ADE20k or cityscapes datasets?

**Comment by qubvel** [comment]
Hi @Prakashvanapalli there is a little chance, but it is not a main purpose.
There are a lot of models pretrained on coco/ade20k/etc, you can found them on github, the aim of this repo is to provide you with model for your specific task (ptretrained encoder just improve convergence and reduce overfitting).

**Comment by Prakashvanapalli** [comment]
Hi @qubvel . Thanks for your reply. I have searched through google but couldn't find anything relevant so far especially for cocostuff. Anyway, thanks again :)
