### ISSUE TITLE
Backbones

### ISSUE THREAD

**Issue by nl201864** [qubvel/segmentation_models#94]
Could you please explain the work of backbones? Why do we have 5 skip connections and 5 upsample layers for Unet + VGG backbones and 5 upsample blocks and 4 connections for other backbones? I've tried to change the number of upsample blocks for 4 for ResNet backbone but got the error with shapes, do you know possible reasons for that?

**Comment by qubvel** [comment]
Hi @nl201864 
All backbones have 5 downslampling stages (pooling or conv+stride), however only VGG has convolution layers before first downsampling, other backbones usually have conv7x7+stride2 operation as a first, so there are no any features for skip connection for these architectures.

**Comment by qubvel** [comment]
That is why these architectures have 5 upsampling blocks (to have same shape as input) and only 4 skip connections.

**Comment by nl201864** [comment]
I got it, thank you for this explanation!
